package crunchypencil.com.tarot1;
/**
 * Created by davidcahill on 11/12/14.
 */
public class Deck {
    static boolean soundon = true;
    static int count = 0;
    static int[] tempdeck = new int[78]; // length of the deck

    static int[] temparray = Deck.makeArray(); // make dummy array to shuffle
    public static int[] makeArray() {
        int[] sample = new int[Deck.tempdeck.length];
        for (int i = 0; i < sample.length; i++) {
            sample[i] = i;
        }
        return sample;
    }
    public static int[] shuffleArray(int[] numbers) {
        for (int i = numbers.length - 1; i> 0; i--) {
            int select = (int) (Math.random() * (i + 1)); // 0 <= select <= i
            // swap current value with selected value
            int temp = numbers[i];
            numbers[i] = numbers[select];
            numbers[select] = temp;
        }
        return numbers;
    }

    static String[][] tarotdeck = new String[78][];
    public static String[][] addFlip(String[][] decktoadd){
        for(int i=0;i<78;i++){
            double invran = Math.random();
            if (invran <= .5) {
                decktoadd[i][1] = "false";
            } else {
                decktoadd[i][1] = "true";
            }
        }
        return decktoadd;
    }

    static String[][] deck = new String[][] {
            { "0 - The Fool",
                    "maj00",
                    "maj00",
                    "maj00",
                    "With light step, a young man in garish vestments pauses at the brink of a precipice. He surveys the expanse of the sky rather than the edge below, as if angels would uphold him if he stepped from the height. His expression is of a dream, with a rose in one hand and in the other a staff, suspending his possessions, accompanied by a dog, as distracted as he is.",
                    "Beginnings, innocence, spontaneity, a free spirit, folly, optimism, delirium. This card suggests new possibilities but beware of foolishness.",
                    "Reversed: Negligence, naivety, recklessness, risk-taking, carelessness, apathy, vanity. This card represents failure due to foolish behavior."
            },
            { "I - The Magician",
                    "maj01",
                    "maj01",
                    "maj01",
                    "A youthful figure in a robe with a look of confidence upholds a wand in front of a table in a garden. His other hand points to the ground. Above his head is the mysterious sign of infinity and his belt is a serpent biting its own tail. On the table in front of him are the symbols of the four suits, signifying the elements of natural life.",
                    "Power, skill, concentration, action, resourcefulness, diplomacy, self-confidence. This card represents creation by willpower and desire.",
                    "Reversed: Manipulation, poor planning, latent talents, disgrace, disquiet. This card represents empty promises and illusions."
            },
            { "II - The High Priestess",
                    "maj02",
                    "maj02",
                    "maj02",
                    "She has the lunar crescent at her feet, a horned diadem on her head with a globe in the middle, and a large solar cross on her breast. The scroll in her hands is inscribed with the word TORA, signifying the Law and the Word. She is seated between a white and a black pillar inscribed with a J and a B. She is the spiritual Bride and Mother, the Daughter of the Stars.",
                    "Intuition, the subconscious, secrets, the future as yet unrevealed, gain knowledge. This card represents a journey to enlightenment.",
                    "Reversed: Passion, hidden agendas, conceit, surface knowledge. This card represents breaking through illusion, revealing damaging secrets.",
            },
            { "III - The Empress",
                    "maj03",
                    "maj03",
                    "maj03",
                    "A stately figure seated with rich vestments, she is a daughter of Heaven and Earth. Her diadem is of twelve stars, gathered in a cluster. The symbol of Venus is on the shield which rests near her. She is in a garden growing grain in front of a waterfall. She is the inferior Garden of Eden, the Earthly Paradise.",
                    "Fertility, femininity, beauty, nature, abundance, action, initiative. This card represents a person who is a protective incubator of creativity.",
                    "Reversed: Creative block, dependence on others. This card represents the destruction of thriving entities.",
            },
            { "IV - The Emperor",
                    "maj04",
                    "maj04",
                    "maj04",
                    "He has an Ankh for his scepter and a globe in his left hand. He is a crowned monarch, stately seated on a throne, the arms of which are fronted by rams' heads. He is executive and realization, the power of this world, clothed in authority.",
                    "Father-figure, stability, power, protection, reason, conviction. This card suggests the authority to command.",
                    "Reversed: Rigidity, inflexibility, obstruction, loss of authority. This card suggests that concentration and focus is vital now.",
            },
            { "V - The Hierophant",
                    "maj05",
                    "maj05",
                    "maj05",
                    "He wears a triple crown and is seated between two pillars. He holds a scepter terminating in the triple cross, and with his right hand he gives the ecclesiastical sign. At his feet are crossed keys and two priestly ministers kneeling before him.",
                    "Alliance, captivity, religion, society, beliefs. This card represents surrendering to tradition rather than asserting uniqueness.",
                    "Reversed: Restriction, challenging the status quo. This card suggests that hose who were once below can become the master.",
            },
            { "VI - The Lovers",
                    "maj06",
                    "maj06",
                    "maj06",
                    "The sun shines in the zenith, and beneath is a great winged figure with arms extended. In the foreground are Adam and Eve when they first occupied the garden of Eden. Behind the man is the Tree of Life, bearing twelve fruits, and the Tree of the Knowledge of Good and Evil is behind the woman with the serpent.",
                    "Attraction, sexuality, love, union, relationships. This card represents finding the other half that makes a whole.",
                    "Reversed: Failure, foolish designs, disharmony, imbalance, misalignment of values. This card represents earthly desires taking hold.",
            },
            { "VII - The Chariot",
                    "maj07",
                    "maj07",
                    "maj07",
                    "An erect and princely figure is crowned and at the control of a chariot. He has led a conquest of the mind, in science, in progress and in trials of initiation. Two sphinxes are at rest. They draw his chariot.",
                    "Movement, progress, providence, war, triumph, will power, victory, assertion. This card represents taking control and direction.",
                    "Reversed: Riot, quarrel, dispute, lack of control. This card suggests that here is no winning this war.",
            },
            { "VIII - Strength",
                    "maj08",
                    "maj08",
                    "maj08",
                    "A woman is calmly closing the jaws of a lion. Over her head is the symbol of life, seen in the card of the Magician.",
                    "Power, energy, courage, patience, control, integration of the animal self. Understand your wild natures and embrace them.",
                    "Reversed: Weakness, self-doubt, lack of self-discipline, discord. This card represents a beast that cannot be controlled.",
            },
            { "IX - The Hermit",
                    "maj09",
                    "maj09",
                    "maj09",
                    "The Hermit is said to be in search of Truth, and of Justice which has preceded him on the way. His lantern contains the Light of Inner Guidance and he carries the staff of Wisdom.",
                    "Meditation, prudence, soul-searching, introspection, being alone. A time for inner guidance and solitude.",
                    "Reversed: Concealment, disguise, isolation, withdrawal. In the dark and alone. Avoid spending time in solitude.",
            },
            { "X - Wheel of Fortune",
                    "maj10",
                    "maj10",
                    "maj10",
                    "The magical beasts surrounding the wheel embody knowledge. This symbolic picture stands for the perpetual motion of a fluidic universe and for the flux of human life. The word TARO can be reversed and read as ROTA, inscribed on the wheel.",
                    "Destiny, fortune, success, good luck, karma, life cycles, destiny, a turning point. A change that brings good fortune.",
                    "Reversed: Bad luck, lack of control, negative external forces, chaos. Good times or bad times will pass.",
            },
            { "XI - Justice",
                    "maj11",
                    "maj11",
                    "maj11",
                    "The figure is seated between the pillars of Justice. He upholds a sword and scales, representing Fairness and Law.",
                    "Equity, triumph of the deserving side in law, fairness, truth, cause and effect. This card represents sharing; excesses have their consequences.",
                    "Reversed: Complications, unfairness, dishonesty. This card represents the acceptance of injustice; there may be nothing one can do to change.",
            },
            { "XII - The Hanged Man",
                    "maj12",
                    "maj12",
                    "maj12",
                    "The gallows from which he is suspended forms a cross. There is an aura about the head of this martyr. This figure suggests life in suspension, not death. He is deep in meditation, accepting his fate and wiser for it.",
                    "Wisdom, trials, surrender, sacrifice, intuition, a new perspective, letting go. This card represents new perspectives that come with selflessness.",
                    "Reversed: Martyrdom, indecision, delay. This card represents stubbornness or selfishness and clinging to the Ego.",
            },
            { "XIII - Death",
                    "maj13",
                    "maj13",
                    "maj13",
                    "The mysterious horseman moves slowly, bearing a black banner emblazoned with the Mystic Rose which signifies life. Between two pillars on the horizon shines the sun of immortality. He carries no weapon, but king and child and maiden fall before him, while a prelate with clasped hands awaits his end.",
                    "End, mortality, change, transformation, transition. This card represents endings, possibly of a life. Rebirth is at the end of a tunnel.",
                    "Reversed: Lethargy, resistance to change, desecration. This card represents a grief that cannot be dealt with or overcome.",
            },
            { "XIV - Temperance",
                    "maj14",
                    "maj14",
                    "maj14",
                    "A winged angel, with the sign of the sun upon his forehead and on his breast a square and triangle. He is pouring the essence of life from chalice to chalice. He has one foot upon the earth and one upon water. A direct path goes up to the horizon and a great light, through which a crown is seen.",
                    "Economy, moderation, frugality, balance, patience, synthesis. This card represents creating an unique element out of opposing elements.",
                    "Reversed: Competing interests, imbalance. One must do what it takes to find balance and understand the practical side of problems.",
            },
            { "XV - The Devil",
                    "maj15",
                    "maj15",
                    "maj15",
                    "The great Horned Goat with wings like a bat is standing on an altar. The right hand is upraised and extended, the reverse of the benediction given by the Hierophant. In the left hand there is a great flaming torch pointing towards the earth. A reversed pentagram is on his forehead. A ring on the altar chains two devil figures, male and female.",
                    "Ravage, bondage, addiction, sexuality, materialism. This card represents temptations and a refusal to escape our bonds.",
                    "Reversed: Breaking free, detachment, power reclaimed. This card represents bondage freed and evil dethroned.",
            },
            { "XVI - The Tower",
                    "maj16",
                    "maj16",
                    "maj16",
                    "The Tower is struck by lightning, exploding and set afire, blowing off the crown on top. Its two inhabitants fall to the depths below.",
                    "Unforeseen catastrophe, collapse of stable structures, upheaval. This card represents anything we believe to be true but we later learn is false.",
                    "Reversed: Avoidance of disaster, fear of change. This card suggests that one has avoided a catastrophe and should breathe a sigh of relief.",
            },
            { "XVII - The Star",
                    "maj17",
                    "maj17",
                    "maj17",
                    "A great, radiant star, surrounded by seven lesser stars. The female figure in the foreground is naked. Her left knee is on the land and her right foot upon the water. She pours Water of Life from two great ewers, irrigating sea and land.",
                    "Hope and bright prospects, calm, a good omen, renewal, inspiration. This card suggests a look to the future with confidence and healing.",
                    "Reversed: Lack of faith, despair, discouragement. This card suggests a look to the future with a loss or false hope.",
            },
            { "XVIII - The Moon",
                    "maj18",
                    "maj18",
                    "maj18",
                    "The moon's eyes are closed as if asleep, between two towers. A dog and a wolf howl and are accompanied by a crustacean emerging from the waters. They are the fears of the natural mind; the reflected light of the moon illuminating our animal nature.",
                    "Mystery, illusion, fear, anxiety, dreams, subconscious, intuition. This card represents a time of emotional or mental trial.",
                    "Reversed: Release of fear, unhappiness, confusion. Be aware of criminals and those with dark intentions.",
            },
            { "XIX - The Sun",
                    "maj19",
                    "maj19",
                    "maj19",
                    "A naked child mounted on a white horse with flowers in his hair upholds a pennant in a garden of sunflowers. It signifies the light of this world, typified by the heart of a child.",
                    "Material happiness, warmth, success. 'Seeing one's day in the sun'. This card represents glory, triumph, simple pleasures and truths.",
                    "Reversed: Lack of clarity, disorder, anarchy, frustration. This card represents arguments, twisted and taken out of context.",
            },
            { "XX - Judgment",
                    "maj20",
                    "maj20",
                    "maj20",
                    "A great angel is encompassed by clouds, blowing his trumpet with a cross displayed on its banner. Below the dead are rising from their tombs.",
                    "Change of position, renewal, rebirth, inner calling. This card represents an error in the past. Resurrect it, forgive it and let it go.",
                    "Reversed: Weakness, self-doubt, refusal of self-examination. This card suggests that something thought finished has reappeared.",
            },
            { "XXI - The World",
                    "maj21",
                    "maj21",
                    "maj21",
                    "The four living creatures of the Apocalypse, attributed to the evangelists in Christian symbolism, are grouped about an elliptical garland. Within is the figure of a woman, wearing only a light scarf. In the act of dancing, she has a wand in either hand.",
                    "Assured success, voyage, emigration, completion, scholarship. This card represents travel to dispense knowledge and accomplishments.",
                    "Reversed: Stagnation, lack of completion, lack of closure. This card represents what has been started is not complete.",
            },
            { "Ace of Wands",
                    "minw01",
                    "minw01",
                    "minw01",
                    "A magical hand immerging from a cloud or puff of smoke upholds a wand growing with leaves.",
                    "Creation, invention, enterprise, beginning, the starting point of enterprises, potential. This card represents success that will arrive soon.",
                    "Reversed: Fall, delay, lack of motivation. This card represents that it may be difficult to keep focus.",
            },
            { "Two of Wands",
                    "minw02",
                    "minw02",
                    "minw02",
                    "A tall man looks from a battlemented roof over a seashore. He holds a globe in his right hand and a staff in his left rests on the battlement. The second staff is fixed upright in a ring. A rose, a cross and a lily are shown in an emblem.",
                    "Contemplation, future planning, progress. This card represents an intuitive choice of instinct; two possibilities, equally good.",
                    "Reversed: Fear of the unknown, lack of planning. This card represents prevention from seeing a difference between possibilities.",
            },
            { "Three of Wands",
                    "minw03",
                    "minw03",
                    "minw03",
                    "A calm, stately personage with his back turned, looking from a cliff's edge at ships passing over the sea. Three staves are planted in the ground, and he leans slightly on one of them.",
                    "Preparation, safety, foresight, enterprise, the home. This card represents work that pays off. Efforts are seen and appreciated.",
                    "Reversed: Lack of foresight. This card may represent an anticipated reward that cannot come.",
            },
            { "Four of Wands",
                    "minw04",
                    "minw04",
                    "minw04",
                    "From the four staves planted in the foreground there is a great garland suspended. Two female figures uplift bouquets. At their side is a bridge over a moat, leading to an old castle.",
                    "Celebration, harmony, a marriage, home, community. This card represents a foundation to be built upon.",
                    "Reversed: An unsound foundation, disharmony. This card suggests that something is not solid about a relationship.",
            },
            { "Five of Wands",
                    "minw05",
                    "minw05",
                    "minw05",
                    "A group of youths, brandishing staves are fighting in sport or in strife. It is mimic warfare.",
                    "Disagreement, strife, tension, minor conflict. Don't be afraid of competition or a struggle to stand out among others.",
                    "Reversed: Conflict avoidance, diversity, agreeing to disagree. A person who has no faith in winning a struggle doesn't try.",
            },
            { "Six of Wands",
                    "minw06",
                    "minw06",
                    "minw06",
                    "A laurelled horseman bears a staff adorned with a laurel crown. Footmen with staves are at his side.",
                    "Victory, progress, self-confidence, achievement. This card represents receiving a recognition that is deserved.",
                    "Reversed: Egotism, lack of confidence, achievement delayed. This card may represent a victory, but delayed or achieved with no applause.",
            },
            { "Seven of Wands",
                    "minw07",
                    "minw07",
                    "minw07",
                    "A young man on a cliff is brandishing a staff as if fighting six other staves, raised towards him from below.",
                    "Defensiveness, on-guard, challenge, competition. This card represents defending a position, even if it is unpopular",
                    "Reversed: Giving up, overwhelmed, overly protective, anxiety. This card represents an inability to defend, folding under pressure.",
            },
            { "Eight of Wands",
                    "minw08",
                    "minw08",
                    "minw08",
                    "The card represents motion through the immovable - a flight of wands speeding through an open country.",
                    "Speed, action, air travel, movement. This card suggests that change will arrive quickly and things will fall into place.",
                    "Reversed: Delays, frustration, holding off, unmotivated. This card suggests that some things cannot be rushed.",
            },
            { "Nine of Wands",
                    "minw09",
                    "minw09",
                    "minw09",
                    "A figure with a bandage on his head leans upon his staff and has an expectant look, as if awaiting an enemy. Behind are eight other staves—erect, in orderly disposition.",
                    "Worry, pessimism, persistence, test of faith, resilience, last stand. There is no giving up or going back.",
                    "Reversed: On edge, defensive, hesitant, wasted hope. Nobody is coming to help.",
            },
            { "Ten of Wands",
                    "minw10",
                    "minw10",
                    "minw10",
                    "A man is oppressed by the weight of the ten staves he is attempting to carry.",
                    "Responsibilities, hard work, stress. You carry a heavy burden. Lighten your load and give yourself a break.",
                    "Reversed: Taking on too much, avoiding responsibility. This card represents a neglected duty, passing the responsibility on to others.",
            },
            { "Page of Wands",
                    "minw11",
                    "minw11",
                    "minw11",
                    "A young man stands in the act of proclamation, inspired by the staff he is holding.",
                    "Inspiration, enthusiasm, exploration, discovery, free spirit. This card may represent a newcomer, easily distracted or a message regarding travel.",
                    "Reversed: Pessimism, lack of direction. This card may represent a newcomer who uses their temper to get their way, or a message of a setback.",
            },
            { "Knight of Wands",
                    "minw12",
                    "minw12",
                    "minw12",
                    "He is upon a journey, armed with a short wand, and although armored, he is not warlike. The motion of the horse is a key to the character of its rider.",
                    "Energy, passion, risk-taker, lust, action, adventure, impulsiveness. This card may represent a charismatic individual who leads.",
                    "Reversed: Setbacks, frustration, intimidation. This card may represent an influential bully who wants to win at any cost.",
            },
            { "Queen of Wands",
                    "minw13",
                    "minw13",
                    "minw13",
                    "The Queen sits upon a decorated throne with a staff and a sunflower, accompanied by a black cat. Her face is confident and determined.",
                    "Exuberance, warmth, fertility, vibrancy, determination. This card may represent an influential woman who is well-connected makes things happen.",
                    "Reversed: Ignorance, intimidation, loss of faith. This card may represent a woman with a terrible temper who will lash out when crossed.",
            },
            { "King of Wands",
                    "minw14",
                    "minw14",
                    "minw14",
                    "The king is a serious man; an animated, impassioned, noble. He holds a flowering wand. He connects with the symbol of the lion, which is emblazoned on the back of his throne. A lizard is at his feet and also on his throne.",
                    "Career-focused, entrepreneur, honor. This card may represent a charismatic and influential leader with the support of all.",
                    "Reversed: Dictator, chaos, opposition to change. This card may represent an influential leader with support through the use of fear.",
            },
            { "Ace of Pentacles",
                    "minp01",
                    "minp01",
                    "minp01",
                    "A mystical hand issuing from a cloud or puff of smoke holds up a pentacle above a garden of flowers.",
                    "Manifestation, prosperity, gifts, fortune. This card suggests new beginnings and a financial turn for the better.",
                    "Reversed: Lost opportunity, lack of planning and foresight. This card suggests that one should not worry too much about money.",
            },
            { "Two of Pentacles",
                    "minp02",
                    "minp02",
                    "minp02",
                    "A young man in the act of dancing has a pentacle in either hand. They are joined by an endless cord which is like the infinity symbol of The Magician card.",
                    "Balance, adaptability, time management, prioritization. Avoid multitasking and trying to handle too many things.",
                    "Reversed: Disorganization, financial disarray. You cannot deal with everything on your plate. Take a break.",
            },
            { "Three of Pentacles",
                    "minp03",
                    "minp03",
                    "minp03",
                    "A sculptor is at his work in a monastery. This apprentice has received his payment and is now at work in earnest, accompanied by admirers of his craft.",
                    "Teamwork, initial fulfillment, collaboration, learning, suitable career. Those around you appreciate your hard work.",
                    "Reversed: Lack of teamwork, disregard for skills. Now is not the time to slack off or be sloppy.",
            },
            { "Four of Pentacles",
                    "minp04",
                    "minp04",
                    "minp04",
                    "A crowned figure has a pentacle over his crown, he clasps another with hands and arms. Two pentacles are under his feet. He holds on to that which he has.",
                    "False security, possession, conservatism. Looking carefully at what you are clinging to. 'If you love something, set it free'.",
                    "Reversed: Materialism, self-protection. This card represents a person throwing away all their money, keeping nothing for a rainy day.",
            },
            { "Five of Pentacles",
                    "minp05",
                    "minp05",
                    "minp05",
                    "Two beggars in a snowstorm pass a church with a lighted window bearing five pentacles.",
                    "Isolation, insecurity, worry, financial loss, poverty, feeling as an outsider. Reach out and ask for help. It will come.",
                    "Reversed: Recovery from financial loss. This card represents the end of a period of pain with nobody's help. It is in the past now.",
            },
            { "Six of Pentacles",
                    "minp06",
                    "minp06",
                    "minp06",
                    "A merchant weighs money in a pair of scales and distributes it to the needy and distressed. It is a testimony to his own success in life.",
                    "Generosity, charity, accepting and giving help, prosperity. Share your wealth, there is always someone who needs it.",
                    "Reversed: Debt, one-sided charity. Accept the help that is available in order to survive.",
            },
            { "Seven of Pentacles",
                    "minp07",
                    "minp07",
                    "minp07",
                    "A young man, leaning on his staff, looks intently at seven pentacles attached to a clump of greenery on his right. One might infer that these were his treasures and his investments growing.",
                    "Vision, perseverance, profit, investment. This card represents waiting for plans to bear fruit; reaping what has been sown.",
                    "Reversed: Lack of long-term vision, limited success or reward. This card represents self-sabotage through a lack of patience.",
            },
            { "Eight of Pentacles",
                    "minp08",
                    "minp08",
                    "minp08",
                    "An artist is at craft, which he exhibits in the form of trophies displayed on a tree.",
                    "Work, employment, apprenticeship, laying the groundwork. This card represents a period of very hard work and necessary efforts.",
                    "Reversed: Voided ambition, lacking focus, lacking foundation. This card represents work that is tedious, learning or gaining nothing.",
            },
            { "Nine of Pentacles",
                    "minp09",
                    "minp09",
                    "minp09",
                    "A woman with a bird upon her wrist stands amidst an abundance of grapevines in the garden of a manor. It is a luxurious domain, suggesting plenty in all things.",
                    "Gratitude, luxury, self-sufficiency, material comforts. This card represents financial worries of the near past that are over for a while.",
                    "Reversed: Solitude, loneliness, a price to pay, a prisoner. This card may represent a lack of comfort in the home.",
            },
            { "Ten of Pentacles",
                    "minp10",
                    "minp10",
                    "minp10",
                    "A man and woman beneath an archway gives entrance to a house and domain. They are accompanied by a child, who looks curiously at their two dogs accosting an ancient person seated in the foreground.",
                    "Gain, inheritance, family, business relationships. This card represents fortunes passed on to the next generation or to benefit others.",
                    "Reversed: Financial failure, loneliness, loss. This card represents fortunes lost or a legacy wasted.",
            },
            { "Page of Pentacles",
                    "minp11",
                    "minp11",
                    "minp11",
                    "A youthful figure, looking intently at the pentacle which hovers over his raised hands. He moves slowly, insensible of that which is about him.",
                    "Application, a student, focus. This card may represent a hardworking and organized newcomer or a message of good luck.",
                    "Reversed: Lack of progress and planning, short-term focus. This card may represent a miserly newcomer, unhelpful or a message of bad news.",
            },
            { "Knight of Pentacles",
                    "minp12",
                    "minp12",
                    "minp12",
                    "Armored, the Knight rides a slow, enduring, heavy horse. He exhibits his symbol, but does not look at it.",
                    "Utility, serviceableness, methodical, practical, financial. This card may represent an individual who achieves through diligence and hard work.",
                    "Reversed: Idleness, carelessness, laziness. This card may represent an individual who is a slacker, envious of success.",
            },
            { "Queen of Pentacles",
                    "minp13",
                    "minp13",
                    "minp13",
                    "A solitary woman sits upon a throne decorated with goats and angels. She is in a garden, accompanied by a rabbit. In her hand she contemplates the Pentacle.",
                    "Generosity, motherly, grounded, calm, down-to-earth. This card may represent a woman who gets things done practically.",
                    "Reversed: Imbalance in work and family commitments. This card may represent a woman who insists on perfection with no sympathy for others.",
            },
            { "King of Pentacles",
                    "minp14",
                    "minp14",
                    "minp14",
                    "The King holds his scepter; his face is rather dark, suggesting both courage and lethargy as he contemplates the pentacle. He sits upon a throne decorated with bull's heads in front of his elaborate castle.",
                    "Security, abundance, financially secure. This card may represent a hardworking figure of authority. It is best to get to know this man.",
                    "Reversed: Authoritative, fearful, conservative. This card may represent a conservative figure of authority who fears change.",
            },
            { "Ace of Cups",
                    "minc01",
                    "minc01",
                    "minc01",
                    "A hand issues from the cloud, holding in its palm the cup, from which four streams are pouring to the waters beneath, filled with water lilies. A dove, bearing in its bill a cross-marked Host, descends to place the Wafer in the Cup.",
                    "Love, compassion, creativity, overwhelming emotion. New beginnings in the near future. This card represents a good time to make friends.",
                    "Reversed: This card represents blocked or repressed emotions. Reflect on how to remove these.",
            },
            { "Two of Cups",
                    "minc02",
                    "minc02",
                    "minc02",
                    "A youth and maiden are pledging their love to one another, and above their cups rises the symbol of Hermes with a lion's head.",
                    "Unified love, romance, attraction, relationships, compatibility. This card suggests that a partnership is going well.",
                    "Reversed: Incompatibility. This card suggests a danger in the balance between love interests and friends.",
            },
            { "Three of Cups",
                    "minc03",
                    "minc03",
                    "minc03",
                    "Maidens in a garden with cups uplifted, as if pledging to one another.",
                    "Celebration, friendship, community, laughter. This card represents a pleasant reunion with friends who have been apart for some time.",
                    "Reversed: A reunion with old friends, but the celebration goes sour. Stay in touch with people now.",
            },
            { "Four of Cups",
                    "minc04",
                    "minc04",
                    "minc04",
                    "A young man is seated under a tree and contemplates three cups set on the grass before him. A mystical arm issuing from a cloud offers him another cup. His expression is one of apathy or discontent with his environment.",
                    "Meditation, contemplation, apathy, re-evaluation. Beware of boredom; losing focus on the value of what one already has.",
                    "Reversed: Boredom, missed opportunity, acting aloof. It is time to get moving out of a self-imposed rut.",
            },
            { "Five of Cups",
                    "minc05",
                    "minc05",
                    "minc05",
                    "A dark, cloaked figure, looking sideways at three spilled cups. Two others stand upright behind him. A bridge is in the background, leading to a small castle.",
                    "Loss, regret, disappointment, despair, self pity. Do not regret losses; rather value what you have.",
                    "Reversed: Moving on, acceptance, forgiveness. Move on and recover from a loss, otherwise regret will cause more pain.",
            },
            { "Six of Cups",
                    "minc06",
                    "minc06",
                    "minc06",
                    "Children in a garden, their six cups are filled with flowers.",
                    "Sentimentality, nostalgia, memories, innocence, childhood. One should not waste time reflecting on the past.",
                    "Reversed: Misery and problems in the past. It is best to stay focused on the present and the future.",
            },
            { "Seven of Cups",
                    "minc07",
                    "minc07",
                    "minc07",
                    "Strange chalices filled with spiritual emblems are shown to an individual experiencing a mystical vision.",
                    "Wishful thinking, choices, indecision. Narrow your focus. This card represents a variety of tempting options; some are unrealistic.",
                    "Reversed: Stuck and going nowhere. This card represents limited options or a depression and downward spiral. ",
            },
            { "Eight of Cups",
                    "minc08",
                    "minc08",
                    "minc08",
                    "A man is secretly deserting the foreground of eight cups, escaping at night.",
                    "Escapism, disappointment. It is in the best interest to abandon something in search of something better.",
                    "Reversed: Hopelessness, aimless drifting, walking away. This card represents abandoning something due to a hopeless situation.",
            },
            { "Nine of Cups",
                    "minc09",
                    "minc09",
                    "minc09",
                    "A rich man is happy with the abundant refreshment of wine on the table behind him. He is assured material satisfaction.",
                    "Wishes fulfilled, comfort, happiness, indulgence, self-satisfaction. This card represents a 'yes' answer.",
                    "Reversed: Misery and pain, disruption of the family, a free-for-all. It may be best to cut ties.",
            },
            { "Ten of Cups",
                    "minc10",
                    "minc10",
                    "minc10",
                    "The appearance of Cups in a rainbow, contemplated by a man and woman below. The two children dancing near them have not observed this marvel but are happy in their own way.",
                    "Harmony, marriage, happiness, attainment. A happy family or extended family of friends.",
                    "Reversed: Disruption of harmony, eating away at the heart of a family.",
            },
            { "Page of Cups",
                    "minc11",
                    "minc11",
                    "minc11",
                    "A fair young man, lavishly dressed, contemplates a fish rising from a cup to speak to him.",
                    "Inspiration, creativity, synchronicity, learning artistic skill. This card may represent a newcomer with the soul of a poet or a message of affection.",
                    "Reversed: Emotional immaturity, creative block. This card may represent a moody newcomer, hard to motivate, or a message of a break-up.",
            },
            { "Knight of Cups",
                    "minc12",
                    "minc12",
                    "minc12",
                    "Graceful but not warlike, the knight rides quietly wearing a winged helmet. He is a dreamer, following his vision in the cup.",
                    "Romance, charm, creativity, artistic skill. This card may represent a Good Samaritan bearing good news coming soon.",
                    "Reversed: Depression, resentment. This card may represent a cynical individual using their insight to harm others.",
            },
            { "Queen of Cups",
                    "minc13",
                    "minc13",
                    "minc13",
                    "A beautiful woman sits on a throne at the edge of the sea. Her feet do not touch the water. She stares at a cup she cradles in her hands with handles shaped like praying angels.",
                    "Emotional security, love, compassion. This card may represent a woman who is supportive, solving problems through empathy and affection.",
                    "Reversed: Emotional insecurity, co-dependency. This may represent a woman whose energy has become angry or untrustworthy and manipulative.",
            },
            { "King of Cups",
                    "minc14",
                    "minc14",
                    "minc14",
                    "He holds a short scepter in his left hand and a great cup in his right. His throne is set upon the sea. On one side a ship is sailing and on the other a dolphin is leaping.",
                    "Emotional balance and control, generosity. This card may represent a fatherly figure with balanced energy who cares for everyone elicits loyalty.",
                    "Reversed: Emotional manipulation, volatility. This card may represent an unbalanced, partisan figure with absolute loyalty to his family.",
            },
            { "Ace of Swords",
                    "mins01",
                    "mins01",
                    "mins01",
                    "A hand issues from a cloud, grasping a sword, the point of which is encircled by a crown with hanging laurel.",
                    "A fresh start, opportunity, a new idea. One should not be afraid to take a leap when bravery is called for.",
                    "Reversed: Confusion, chaos, lack of clarity. One should be careful of illusions and whom they trust.",
            },
            { "Two of Swords",
                    "mins02",
                    "mins02",
                    "mins02",
                    "A blinded female figure balances two swords of equal size. She is seated at the shore, beneath a crescent moon.",
                    "Indecision, choices, truce, stalemate, compromise. Consideration must be given to whether or not one is treated as an equal in partnership.",
                    "Reversed: Combat, no compromise is possible. This card suggests a danger in putting too much emphasis on one partnership.",
            },
            { "Three of Swords",
                    "mins03",
                    "mins03",
                    "mins03",
                    "Three swords piercing a heart, clouds and rain behind.",
                    "Painful separation, heartbreak, grief, betrayal. Time is needed to experience pain, but one should not wallow in it.",
                    "Reversed: Optimism, forgiveness, but a likely disappointment. A time to feel pain then move on.",
            },
            { "Four of Swords",
                    "mins04",
                    "mins04",
                    "mins04",
                    "The effigy of a knight in prayer upon his place of burial. His tomb is decorated with swords.",
                    "Meditation, rest, retreat. A need for time and space. One should not hesitate to draw boundaries or to say 'no'.",
                    "Reversed: Burnt-out, exhaustion, isolation. There will be no rest, no recuperation.",
            },
            { "Five of Swords",
                    "mins05",
                    "mins05",
                    "mins05",
                    "A smirking young man looks after two figures who have given up; their swords lie discarded upon the ground. He carries two others on his shoulder, and a third sword is in his hand, pointed to the earth. He has won this contest.",
                    "Conflicts, external or internal, betrayal, losing a fight. Choose your battles. One should not escalate conflicts unnecessarily.",
                    "Reversed: A no-win situation, an argument dragging on. One should focus energy into more productive efforts than conflict.",
            },
            { "Six of Swords",
                    "mins06",
                    "mins06",
                    "mins06",
                    "A ferryman carrying passengers in his boat escaping to the further shore. The water is smooth and passage is assured.",
                    "Leaving. Regretful but necessary travel or transition. A rite of passage, a change for the better. This card represents escaping troubled waters.",
                    "Reversed: Information is critical and communication is difficult. This card suggests an unexpected failure, having to 'swim for it'.",
            },
            { "Seven of Swords",
                    "mins07",
                    "mins07",
                    "mins07",
                    "A man is sneaking away from a nearby camp, in the act of carrying away five swords. The remaining swords of the card are stuck in the ground.",
                    "Secret plans, betrayal, deception. One must keep a close eye out for cheating and for thieves.",
                    "Reversed: Think twice. Crime doesn't pay. Thieves will be caught and must be called to account.",
            },
            { "Eight of Swords",
                    "mins08",
                    "mins08",
                    "mins08",
                    "A woman is bound and blindfolded, imprisoned by the swords of the card about her.",
                    "Powerlessness, isolation, a self-imposed restriction. This card represents holding oneself back for fear of the future or the unknown.",
                    "Reversed: Keep moving. Be open to new perspectives. This card represents the opinions of others causing isolation.",
            },
            { "Nine of Swords",
                    "mins09",
                    "mins09",
                    "mins09",
                    "A woman seated on her couch in lamentation as if awoken from a nightmare, with the swords of the card over her. There is no sorrow like hers.",
                    "An overactive mind, depression, nightmares, anxiety. Anxieties are all in the mind. One must wake up and deal with reality.",
                    "Reversed: Insomnia, ignorance. Ignoring problems is no way to deal with them.",
            },
            { "Ten of Swords",
                    "mins10",
                    "mins10",
                    "mins10",
                    "A man is dead, pierced by all the swords belonging to the card. The sky is dark and the landscape desolate.",
                    "Defeat, sabotage, completion. The matter is ended and the person or the issue at hand is dead. It is time to deal with it or to move on.",
                    "Reversed: Continued pain. Opponents turning the knife. The suffering is not over.",
            },
            { "Page of Swords",
                    "mins11",
                    "mins11",
                    "mins11",
                    "A lithe, active figure holds a sword upright in both hands. He is passing over rugged land. He looks back as if he is unsure of his decision.",
                    "Talkative, restless, acts without thinking. This card may represent a newcomer, chatty and ambitious, a story teller, or a message of solutions.",
                    "Reversed: Unexpected occurrences or conflict. This card may represent a gossiper, a know-it-all spreading stories, or a message of gossip",
            },
            { "Knight of Swords",
                    "mins12",
                    "mins12",
                    "mins12",
                    "He is riding at full speed, as if scattering his foes. Armored, he is out to destroy his enemies with a swift sword; he is certain that he is clean of heart.",
                    "Determined, action-oriented, travel. This card may represent an individual who changes the world through quick wit and cleverness.",
                    "Reversed: Intelligence but unable to communicate. Be cautious sharing with an individual who hides behind false pretenses.",
            },
            { "Queen of Swords",
                    "mins13",
                    "mins13",
                    "mins13",
                    "Her right hand holds the weapon vertically and the hilt rests on an arm of her throne. Her left hand is extended, the arm raised. Her countenance is severe but chastened. The expression suggests familiarity with sorrow, but not with mercy.",
                    "A quick thinker, organized, perceptive, wisdom. This card may represent a woman of cool intelligence; a communicative problem solver.",
                    "Reversed: Malice, cold-heartedness, distant, miscommunication. This card may represent an influential woman, aloof and cruel who fails to communicate.",
            },
            { "King of Swords",
                    "mins14",
                    "mins14",
                    "mins14",
                    "The king sits in judgment as the authoritarian, upon a throne upholding a raised sword. Although similar to the symbol of justice, he is more alike to the powers over life and death.",
                    "Serious, clear thinking, authority, power. Take care not to overextend your reach. This card may represent a man full of forceful, opinionated energy.",
                    "Reversed: Manipulative, forceful energy. This card may represent bullying, censorship or the manipulation of facts.",
            }
    };
} 