package crunchypencil.com.tarot1;

/**
 * Created by davidcahill on 11/12/14.
 */

public class Deck {

    static int count = 0;

    static int[] tempdeck = new int[78]; // length of the deck

    static int[] temparray = Deck.makeArray(); // make dummy array to shuffle

    public static int[] makeArray() {
        int[] sample = new int[Deck.tempdeck.length];
        for (int i = 0; i < sample.length; i++) {
            sample[i] = i;
        }
        return sample;
    }

    public static int[] shuffleArray(int[] numbers) {

        for (int i = numbers.length - 1; i > 0; i--) {
            int select = (int) (Math.random() * (i + 1)); // 0 <= select <= i

            // swap current value with selected value
            int temp = numbers[i];
            numbers[i] = numbers[select];
            numbers[select] = temp;
        }
        return numbers;
    }

    static String[][] tarotdeck = new String[][] {
            {	"0 - The Fool",
                    "maj00",
                    "maj00",
                    "maj00",
                    "With light step, as if earth and its trammels had little power to restrain him, a young man in gorgeous vestments pauses at the brink of a precipice among the great heights of the world; he surveys the blue distance before him-its expanse of sky rather than the prospect below. His act of eager walking is still indicated, though he is stationary at the given moment; his dog is still bounding. The edge which opens on the depth has no terror; it is as if angels were waiting to uphold him, if it came about that he leaped from the height. His countenance is full of intelligence and expectant dream. He has a rose in one hand and in the other a costly wand, from which depends over his right shoulder a wallet curiously embroidered. He is a prince of the other world on his travels through this one-all amidst the morning glory, in the keen air. The sun, which shines behind him, knows whence he came, whither he is going, and how he will return by another path after many days. He is the spirit in search of experience.*",
                    "Folly, mania, extravagance, intoxication, delirium, frenzy, bewrayment.",
                    "Reversed: Negligence, absence, distribution, carelessness, apathy, nullity, vanity."
            },
            {	"I - The Magician",
                    "maj01",
                    "maj01",
                    "maj01",
                    "A youthful figure in the robe of a magician, having the countenance of divine Apollo, with smile of confidence and shining eyes. Above his head is the mysterious sign of the Holy Spirit, the sign of life, like an endless cord, forming the figure 8 in a horizontal position (infinity symbol). About his waist is a serpent-cincture, the serpent appearing to devour its own tail. This is familiar to most as a conventional symbol of eternity, but here it indicates more especially the eternity of attainment in the spirit. In the Magician's right hand is a wand raised towards heaven, while the left hand is pointing to the earth. This dual sign is known in very high grades of the Instituted Mysteries; it shews the descent of grace, virtue and light, drawn from things above and derived to things below. The suggestion throughout is therefore the possession and communication of the Powers and Gifts of the Spirit. On the table in front of the Magician are the symbols of the four Tarot suits, signifying the elements of natural life, which lie like counters before the adept, and he adapts them as he wills. Beneath are roses and lilies, the <em>flos campi</em> and <em>lilium convallium</em>, changed into garden flowers, to shew the culture of aspiration.*",
                    "Skill, diplomacy, address, subtlety; sickness, pain, loss, disaster, snares of enemies; self-confidence, will; the Querent, if male.",
                    "Reversed: Physician, Magus, mental disease, disgrace, disquiet."
            },
            {	"II - The High Priestess",
                    "maj02",
                    "maj02",
                    "maj02",
                    "She has the lunar crescent at her feet, a horned diadem on her head, with a globe in the middle place, and a large solar cross on her breast. The scroll in her hands is inscribed with the word <em>Tora</em>, signifying the Greater Law, the Secret Law and the second sense of the Word. It is partly covered by her mantle, to shew that some things are implied and some spoken. She is seated between the white and black pillars—J. and B.—of the mystic Temple, and the veil of the Temple is behind her: it is embroidered with palms and pomegranates. The vestments are flowing and gauzy, and the mantle suggests light—a shimmering radiance. She has been called occult Science on the threshold of the Sanctuary of Isis, but she is really the Secret Church, the House which is of God and man. She represents also the Second Marriage of the Prince who is no longer of this world; she is the spiritual Bride and Mother, the daughter of the stars and the Higher Garden of Eden. She is, in fine, the Queen of the borrowed light, but this is the light of all. She is the Moon nourished by the milk of the Supernal Mother.*",
                    "Secrets, mystery, the future as yet unrevealed; the woman who interests the Querent, if male; the Querent herself, if female; silence, tenacity; mystery, wisdom, science.",
                    "Reversed: Passion, moral or physical ardour, conceit, surface knowledge.",
            },
            {	"III - The Empress",
                    "maj03",
                    "maj03",
                    "maj03",
                    "A stately figure, seated, having rich vestments and royal aspect, as of a daughter of heaven and earth. Her diadem is of twelve stars, gathered in a cluster. The symbol of Venus is on the shield which rests near her. A field of corn is ripening in front of her, and beyond there is a fall of water. The sceptre which she bears is surmounted by the globe of this world. She is the inferior Garden of Eden, the Earthly Paradise, all that is symbolized by the visible house of man.*",
                    "Fruitfulness, action, initiative, length of days; the unknown, clandestine; also difficulty, doubt, ignorance.",
                    "Reversed: Light, truth, the unravelling of involved matters, public rejoicings; according to another reading, vacillation.",
            },
            {	"IV - The Emperor",
                    "maj04",
                    "maj04",
                    "maj04",
                    "He has a form of the <em>Crux ansata</em> for his sceptre and a globe in his left hand. He is a crowned monarch—commanding, stately, seated on a throne, the arms of which axe fronted by rams' heads. He is executive and realization, the power of this world, here clothed with the highest of its natural attributes.*",
                    "Stability, power, protection, realization; a great person; aid, reason, conviction; also authority and will.",
                    "Reversed: Benevolence, compassion, credit; also confusion to enemies, obstruction, immaturity.",
            },
            {	"V - The Hierophant",
                    "maj05",
                    "maj05",
                    "maj05",
                    "He wears the triple crown and is seated between two pillars, but they are not those of the Temple which is guarded by the High Priestess. In his left hand he holds a sceptre terminating in the triple cross, and with his right hand he gives the well-known ecclesiastical sign which is called that of esotericism, distinguishing between the manifest and concealed part of doctrine...At his feet are the crossed keys, and two priestly ministers in albs kneel before him.*",
                    "Marriage, alliance, captivity, servitude; by another account, mercy and goodness; inspiration; the man to whom the Querent has recourse.",
                    "Reversed: Society, good understanding, concord, overkindness, weakness.",
            },
            {	"VI - The Lovers",
                    "maj06",
                    "maj06",
                    "maj06",
                    "The sun shines in the zenith, and beneath is a great winged figure with arms extended, pouring down influences. In the foreground are two human figures, male and female, unveiled before each other, as if Adam and Eve when they first occupied the paradise of the earthly body. Behind the man is the Tree of Life, bearing twelve fruits, and the Tree of the Knowledge of Good and Evil is behind the woman; the serpent is twining round it.*",
                    "Attraction, love, beauty, trials overcome.",
                    "Reversed: Failure, foolish designs. Another account speaks of marriage frustrated and contrarieties of all kinds.",
            },
            {	"VII - The Chariot",
                    "maj07",
                    "maj07",
                    "maj07",
                    "An erect and princely figure carrying a drawn sword... He has led captivity captive; he is conquest on all planes—in the mind, in science, in progress, in certain trials of initiation...two sphinxes thus draw his chariot.*",
                    "Succour, providence also war, triumph, presumption, vengeance, trouble.",
                    "Reversed: Riot, quarrel, dispute, litigation, defeat.",
            },
            {	"VIII - Strength",
                    "maj08",
                    "maj08",
                    "maj08",
                    "A woman, over whose head there broods the same symbol of life which we have seen in the card of the Magician, is closing the jaws of a lion.*",
                    "Power, energy, action, courage, magnanimity; also complete success and honours.",
                    "Reversed: Despotism, abuse if power, weakness, discord, sometimes even disgrace.",
            },
            {	"IX - The Hermit",
                    "maj09",
                    "maj09",
                    "maj09",
                    "The Hermit...is said to be in search of that Truth which is located far off in the sequence, and of justice which has preceded him on the way. But this is a card of attainment, as we shall see later, rather than a card of quest. It is said also that his lantern contains the Light of Occult Science and that his staff is a Magic Wand. ...His beacon intimates that 'where I am, you also may be.'*",
                    "Prudence, circumspection; also and especially treason, dissimulation, roguery, corruption.",
                    "Reversed: Concealment, disguise, policy, fear, unreasoned caution.",
            },
            {	"X - Wheel of Fortune",
                    "maj10",
                    "maj10",
                    "maj10",
                    "...a Hermanubis rising with the wheel, a Sphinx couchant at the summit and a Typhon on the descending side. ...the symbolic picture stands for the perpetual motion of a fluidic universe and for the flux of human life. The Sphinx is the equilibrium therein. The transliteration of <em>Taro</em> as <em>Rota</em> is inscribed on the wheel, counterchanged with the letters of the Divine Name—to shew that Providence is implied through all.*",
                    "Destiny, fortune, success, elevation, luck, felicity.",
                    "Reversed: Increase, abundance, superfluity.",
            },
            {	"XI - Justice",
                    "maj11",
                    "maj11",
                    "maj11",
                    "The figure is seated between pillars, like the High Priestess...the pillars of Justice open into one world and the pillars of the High Priestess into another.*",
                    "Equity, rightness, probity, executive; triumph of the deserving side in law.",
                    "Reversed: Law in all its departments, legal complications, bigotry, bias, excessive severity.",
            },
            {	"XII - The Hanged Man",
                    "maj12",
                    "maj12",
                    "maj12",
                    "The gallows from which he is suspended forms a <em>Tau</em> cross, while the figure—from the position of the legs—forms a fylfot cross. There is a nimbus about the head of the seeming martyr. It should be noted...that the figure, as a whole, suggests life in suspension, but life and not death. It is a card of profound significance, but all the significance is veiled.*",
                    "Wisdom, circumspection, discernment, trials, sacrifice, intuition, divination, prophecy.",
                    "Reversed: Selfishness, the crowd, body politic.",
            },
            {	"XIII - Death",
                    "maj13",
                    "maj13",
                    "maj13",
                    "The mysterious horseman moves slowly, bearing a black banner emblazoned with the Mystic Rose, which signifies life. Between two pillars on the verge of the horizon there shines the sun of immortality. The horseman carries no visible weapon, but king and child and maiden fall before him, while a prelate with clasped hands awaits his end.*",
                    "End, mortality, destruction, corruption also, for a man, the loss of a benefactor for a woman, many contrarieties; for a maid, failure of marriage projects.",
                    "Reversed: Inertia, sleep, lethargy, petrifaction, somnambulism; hope destroyed.",
            },
            {	"XIV - Temperance",
                    "maj14",
                    "maj14",
                    "maj14",
                    "A winged angel, with the sign of the sun upon his forehead and on his breast the square and triangle of the septenary. I speak of him in the masculine sense, but the figure is neither male nor female. It is held to be pouring the essences of life from chalice to chalice. It has one foot upon the earth and one upon waters, thus illustrating the nature of the essences. A direct path goes up to certain heights on the verge of the horizon, and above there is a great light, through which a crown is seen vaguely.*",
                    "Economy, moderation, frugality, management, accommodation.",
                    "Reversed: Things connected with churches, religions, sects, the priesthood, sometimes even the priest who will marry the Querent; also disunion, unfortunate combinations, competing interests.",
            },
            {	"XV - The Devil",
                    "maj15",
                    "maj15",
                    "maj15",
                    "The Horned Goat of Mendes, with wings like those of a bat, is standing on an altar. At the pit of the stomach there is the sign of Mercury. The right hand is upraised and extended, being the reverse of that benediction which is given by the Hierophant in the fifth card. In the left hand there is a great flaming torch, inverted towards the earth. A reversed pentagram is on the forehead. There is a ring in front of the altar, from which two chains are carried to the necks of two figures, male and female. These are analogous with those of the fifth card, as if Adam and Eve after the Fall. Hereof is the chain and fatality of the material life.*",
                    "Ravage, violence, vehemence, extraordinary efforts, force, fatality; that which is predestined but is not for this reason evil.",
                    "Reversed: Evil fatality, weakness, pettiness, blindness.",
            },
            {	"XVI - The Tower",
                    "maj16",
                    "maj16",
                    "maj16",
                    "The Tower struck by Lightning. Its alternative titles are: Castle of Plutus, God's House and the Tower of Babel. In the last case, the figures falling therefrom are held to be Nimrod and his minister.*",
                    "Misery, distress, indigence, adversity, calamity, disgrace, deception, ruin. It is a card in particular of unforeseen catastrophe.",
                    "Reversed: According to one account, the same in a lesser degree also oppression, imprisonment, tyranny.",
            },
            {	"XVII - The Star",
                    "maj17",
                    "maj17",
                    "maj17",
                    "A great, radiant star of eight rays, surrounded by seven lesser stars—also of eight rays. The female figure in the foreground is entirely naked. Her left knee is on the land and her right foot upon the water. She pours Water of Life from two great ewers, irrigating sea and land. Behind her is rising ground and on the right a shrub or tree, whereon a bird alights. The figure expresses eternal youth and beauty.*",
                    "Loss, theft, privation, abandonment; another reading says-hope and bright prospects.",
                    "Reversed: Arrogance, haughtiness, impotence.",
            },
            {	"XVIII - The Moon",
                    "maj18",
                    "maj18",
                    "maj18",
                    "...It has sixteen chief and sixteen secondary rays. The card represents life of the imagination apart from life of the spirit. The path between the towers is the issue into the unknown. The dog and wolf are the fears of the natural mind in the presence of that place of exit, when there is only reflected light to guide it. ...It illuminates our animal nature, types of which are represented below—the dog, the wolf and that which comes up out of the deeps... the message is: Peace, be still; and it may be that there shall come a calm upon the animal nature, while the abyss beneath shall cease from giving up a form.*",
                    "Hidden enemies, danger, calumny, darkness, terror, deception, occult forces, error.",
                    "Reversed: Instability, inconstancy, silence, lesser degrees of deception and error.",
            },
            {	"XIX - The Sun",
                    "maj19",
                    "maj19",
                    "maj19",
                    "The naked child mounted on a white horse...is the destiny of the Supernatural East and the great and holy light which goes before the endless procession of humanity, coming out from the walled garden of the sensitive life and passing on the journey home. The card signifies, therefore, the transit from the manifest light of this world, represented by the glorious sun of earth, to the light of the world to come, which goes before aspiration and is typified by the heart of a child.*",
                    "Material happiness, fortunate marriage, contentment.",
                    "Reversed: The same in a lesser sense.",
            },
            {	"XX - Judgement",
                    "maj20",
                    "maj20",
                    "maj20",
                    "...The great angel is here encompassed by clouds, but he blows his bannered trumpet, and the cross as usual is displayed on the banner. The dead are rising from their tombs—a woman on the right, a man on the left hand, and between them their child, whose back is turned.*",
                    "Change of position, renewal, outcome. Another account specifies total loss though lawsuit.",
                    "Reversed: Weakness, pusillanimity, simplicity; also deliberation, decision, sentence.",
            },
            {	"XXI - The World",
                    "maj21",
                    "maj21",
                    "maj21",
                    "The four living creatures of the Apocalypse and Ezekiel's vision, attributed to the evangelists in Christian symbolism, are grouped about an elliptic garland, as if it were a chain of flowers intended to symbolize all sensible things; within this garland there is the figure of a woman, whom the wind has girt about the loins with a light scarf, and this is all her vesture. She is in the act of dancing, and has a wand in either hand.*",
                    "Assured success, recompense, voyage, route, emigration, flight, change of place.",
                    "Reversed: Inertia, fixity, stagnation, permanence.",
            },
            {	"Ace of Wands",
                    "minw01",
                    "minw01",
                    "minw01",
                    "A hand issuing from a cloud grasps a stout wand or club.",
                    "Creation, invention, enterprise, the powers which result in these; principle, beginning, source; birth, family, origin, and in a sense the virility which is behind them; the starting point of enterprises; according to another account, money, fortune, inheritance.",
                    "Reversed: Fall, decadence, ruin, perdition, to perish also a certain clouded joy.",
            },
            {	"Two of Wands",
                    "minw02",
                    "minw02",
                    "minw02",
                    "A tall man looks from a battlemented roof over sea and shore; he holds a globe in his right hand, while a staff in his left rests on the battlement; another is fixed in a ring. The Rose and Cross and Lily should be noticed on the left side.",
                    "Between the alternative readings there is no marriage possible; on the one hand, riches, fortune, magnificence; on the other, physical suffering, disease, chagrin, sadness, mortification. The design gives one suggestion; here is a lord overlooking his dominion and alternately contemplating a globe; it looks like the malady, the mortification, the sadness of Alexander amidst the grandeur of this world's wealth.",
                    "Reversed: Surprise, wonder, enchantment, emotion, trouble, fear.",
            },
            {	"Three of Wands",
                    "minw03",
                    "minw03",
                    "minw03",
                    "A calm, stately personage, with his back turned, looking from a cliff's edge at ships passing over the sea. Three staves are planted in the ground, and he leans slightly on one of them.",
                    "He symbolizes established strength, enterprise, effort, trade, commerce, discovery; those are his ships, bearing his merchandise, which are sailing over the sea. The card also signifies able co-operation in business, as if the successful merchant prince were looking from his side towards yours with a view to help you.",
                    "Reversed: The end of troubles, suspension or cessation of adversity, toil and disappointment.",
            },
            {	"Four of Wands",
                    "minw04",
                    "minw04",
                    "minw04",
                    "From the four great staves planted in the foreground there is a great garland suspended; two female figures uplift nosegays; at their side is a bridge over a moat, leading to an old manorial house.",
                    "They are for once almost on the surface—country life, haven of refuge, a species of domestic harvest-home, repose, concord, harmony, prosperity, peace, and the perfected work of these.",
                    "Reversed: The meaning remains unaltered; it is prosperity, increase, felicity, beauty, embellishment.",
            },
            {	"Five of Wands",
                    "minw05",
                    "minw05",
                    "minw05",
                    "A posse of youths, who are brandishing staves, as if in sport or strife. It is mimic warfare, and hereto correspond the Divinatory Meanings.",
                    "Imitation, as, for example, sham fight, but also the strenuous competition and struggle of the search after riches and fortune. In this sense it connects with the battle of life. Hence some attributions say that it is a card of gold, gain, opulence.",
                    "Reversed: Litigation, disputes, trickery, contradiction.",
            },
            {	"Six of Wands",
                    "minw06",
                    "minw06",
                    "minw06",
                    "A laurelled horseman bears one staff adorned with a laurel crown; footmen with staves are at his side.",
                    "The card has been so designed that it can cover several significations; on the surface, it is a victor triumphing, but it is also great news, such as might be carried in state by the King's courier; it is expectation crowned with its own desire, the crown of hope, and so forth.",
                    "Reversed: Apprehension, fear, as of a victorious enemy at the gate; treachery, disloyalty, as of gates being opened to the enemy; also indefinite delay.",
            },
            {	"Seven of Wands",
                    "minw07",
                    "minw07",
                    "minw07",
                    "A young man on a craggy eminence brandishing a staff; six other staves are raised towards him from below.",
                    "It is a card of valour, for, on the surface, six are attacking one, who has, however, the vantage position. On the intellectual plane, it signifies discussion, wordy strife; in business—negotiations, war of trade, barter, competition. It is further a card of success, for the combatant is on the top and his enemies may be unable to reach him.",
                    "Reversed: Perplexity, embarrassments, anxiety. It is also a caution against indecision.",
            },
            {	"Eight of Wands",
                    "minw08",
                    "minw08",
                    "minw08",
                    "The card represents motion through the immovable-a flight of wands through an open country; but they draw to the term of their course. That which they signify is at hand; it may be even on the threshold.",
                    "Activity in undertakings, the path of such activity, swiftness, as that of an express messenger; great haste, great hope, speed towards an end which promises assured felicity; generally, that which is on the move; also the arrows of love.",
                    "Reversed: Arrows of jealousy, internal dispute, stingings of conscience, quarrels; and domestic disputes for persons who are married.",
            },
            {	"Nine of Wands",
                    "minw09",
                    "minw09",
                    "minw09",
                    "The figure leans upon his staff and has an expectant look, as if awaiting an enemy. Behind are eight other staves—erect, in orderly disposition, like a palisade.",
                    "The card signifies strength in opposition. If attacked, the person will meet an onslaught boldly; and his build shews, that he may prove a formidable antagonist. With this main significance there are all its possible adjuncts—delay, suspension, adjournment.",
                    "Reversed: Obstacles, adversity, calamity.",
            },
            {	"Ten of Wands",
                    "minw10",
                    "minw10",
                    "minw10",
                    "A man oppressed by the weight of the ten staves which he is carrying.",
                    "A card of many significances, and some of the readings cannot be harmonized. I set aside that which connects it with honour and good faith. The chief meaning is oppression simply, but it is also fortune, gain, any kind of success, and then it is the oppression of these things. It is also a card of false-seeming, disguise, perfidy. The place which the figure is approaching may suffer from the rods that he carries. Success is stultified if the Nine of Swords follows, and if it is a question of a lawsuit, there will be certain loss.",
                    "Reversed: Contrarieties, difficulties, intrigues, and their analogies.",
            },
            {	"Page of Wands",
                    "minw11",
                    "minw11",
                    "minw11",
                    "A young man stands in the act of proclamation. He is unknown but faithful, and his tidings are strange.",
                    "Dark young man, faithful, a lover, an envoy, a postman. Beside a man, he will bear favourable testimony concerning him. A dangerous rival, if followed by the Page of Cups. Has the chief qualities of his suit. He may signify family intelligence.",
                    "Reversed: Anecdotes, announcements, evil news. Also indecision and the instability which accompanies it.",
            },
            {	"Knight of Wands",
                    "minw12",
                    "minw12",
                    "minw12",
                    "He is shewn as if upon a journey, armed with a short wand, and although mailed is not on a warlike errand. He is passing mounds or pyramids. The motion of the horse is a key to the character of its rider, and suggests the precipitate mood, or things connected therewith.",
                    "Departure, absence, flight, emigration. A dark young man, friendly. Change of residence.",
                    "Reversed: Rupture, division, interruption, discord.",
            },
            {	"Queen of Wands",
                    "minw13",
                    "minw13",
                    "minw13",
                    "The Wands throughout this suit are always in leaf, as it is a suit of life and animation. Emotionally and otherwise, the Queen's personality corresponds to that of the King, but is more magnetic.",
                    "A dark woman, countrywoman, friendly, chaste, loving, honourable. If the card beside her signifies a man, she is well disposed towards him; if a woman, she is interested in the Querent. Also, love of money, or a certain success in business.",
                    "Reversed: Good, economical, obliging, serviceable. Signifies also—but in certain positions and in the neighbourhood of other cards tending in such directions—opposition, jealousy, even deceit and infidelity.",
            },
            {	"King of Wands",
                    "minw14",
                    "minw14",
                    "minw14",
                    "The physical and emotional nature to which this card is attributed is dark, ardent, lithe, animated, impassioned, noble. The King uplifts a flowering wand, and wears, like his three correspondences in the remaining suits, what is called a cap of maintenance beneath his crown. He connects with the symbol of the lion, which is emblazoned on the back of his throne.",
                    "Dark man, friendly, countryman, generally married, honest and conscientious. The card always signifies honesty, and may mean news concerning an unexpected heritage to fall in before very long.",
                    "Reversed: Good, but severe; austere, yet tolerant.",
            },
            {	"Ace of Pentacles",
                    "minp01",
                    "minp01",
                    "minp01",
                    "A hand—issuing, as usual, from a cloud—holds up a pentacle.",
                    "Perfect contentment, felicity, ecstasy; also speedy intelligence; gold.",
                    "Reversed: The evil side of wealth, bad intelligence; also great riches. In any case it shews prosperity, comfortable material conditions, but whether these are of advantage to the possessor will depend on whether the card is reversed or not.",
            },
            {	"Two of Pentacles",
                    "minp02",
                    "minp02",
                    "minp02",
                    "A young man, in the act of dancing, has a pentacle in either hand, and they are joined by that endless cord which is like the number 8 reversed.",
                    "On the one hand it is represented as a card of gaiety, recreation and its connexions, which is the subject of the design; but it is read also as news and messages in writing, as obstacles, agitation, trouble, embroilment.",
                    "Reversed: Enforced gaiety, simulated enjoyment, literal sense, handwriting, composition, letters of exchange.",
            },
            {	"Three of Pentacles",
                    "minp03",
                    "minp03",
                    "minp03",
                    "A sculptor at his work in a monastery. Compare the design which illustrates the Eight of Pentacles. The apprentice or amateur therein has received his reward and is now at work in earnest.",
                    "<em>Métier</em>, trade, skilled labour; usually, however, regarded as a card of nobility, aristocracy, renown, glory.",
                    "Reversed: Mediocrity, in work and otherwise, puerility, pettiness, weakness.",
            },
            {	"Four of Pentacles",
                    "minp04",
                    "minp04",
                    "minp04",
                    "A crowned figure, having a pentacle over his crown, clasps another with hands and arms; two pentacles are under his feet. He holds to that which he has.",
                    "The surety of possessions, cleaving to that which one has, gift, legacy, inheritance.",
                    "Reversed: Suspense, delay, opposition.",
            },
            {	"Five of Pentacles",
                    "minp05",
                    "minp05",
                    "minp05",
                    "Two mendicants in a snow-storm pass a lighted casement.",
                    "The card foretells material trouble above all, whether in the form illustrated—that is, destitution—or otherwise. For some cartomancists, it is a card of love and lovers-wife, husband, friend, mistress; also concordance, affinities. These alternatives cannot be harmonized.",
                    "Reversed: Disorder, chaos, ruin, discord, profligacy.",
            },
            {	"Six of Pentacles",
                    "minp06",
                    "minp06",
                    "minp06",
                    "A person in the guise of a merchant weighs money in a pair of scales and distributes it to the needy and distressed. It is a testimony to his own success in life, as well as to his goodness of heart.",
                    "Presents, gifts, gratification another account says attention, vigilance now is the accepted time, present prosperity, etc.",
                    "Reversed: Desire, cupidity, envy, jealousy, illusion.",
            },
            {	"Seven of Pentacles",
                    "minp07",
                    "minp07",
                    "minp07",
                    "A young man, leaning on his staff, looks intently at seven pentacles attached to a clump of greenery on his right; one would say that these were his treasures and that his heart was there.",
                    "These are exceedingly contradictory; in the main, it is a card of money, business, barter; but one reading gives altercation, quarrels—and another innocence, ingenuity, purgation.",
                    "Reversed: Cause for anxiety regarding money which it may be proposed to lend.",
            },
            {	"Eight of Pentacles",
                    "minp08",
                    "minp08",
                    "minp08",
                    "An artist in stone at his work, which he exhibits in the form of trophies.",
                    "Work, employment, commission, craftsmanship, skill in craft and business, perhaps in the preparatory stage.",
                    "Reversed: Voided ambition, vanity, cupidity, exaction, usury. It may also signify the possession of skill, in the sense of the ingenious mind turned to cunning and intrigue.",
            },
            {	"Nine of Pentacles",
                    "minp09",
                    "minp09",
                    "minp09",
                    "A woman, with a bird upon her wrist, stands amidst a great abundance of grapevines in the garden of a manorial house. It is a wide domain, suggesting plenty in all things. Possibly it is her own possession and testifies to material well-being.",
                    "Prudence, safety, success, accomplishment, certitude, discernment.",
                    "Reversed: Roguery, deception, voided project, bad faith.",
            },
            {	"Ten of Pentacles",
                    "minp10",
                    "minp10",
                    "minp10",
                    "A man and woman beneath an archway which gives entrance to a house and domain. They are accompanied by a child, who looks curiously at two dogs accosting an ancient personage seated in the foreground. The child's hand is on one of them.",
                    "Gain, riches; family matters, archives, extraction, the abode of a family.",
                    "Reversed: Chance, fatality, loss, robbery, games of hazard; sometimes gift, dowry, pension.",
            },
            {	"Page of Pentacles",
                    "minp11",
                    "minp11",
                    "minp11",
                    "A youthful figure, looking intently at the pentacle which hovers over his raised hands. He moves slowly, insensible of that which is about him.",
                    "Application, study, scholarship, reflection another reading says news, messages and the bringer thereof; also rule, management.",
                    "Reversed: Prodigality, dissipation, liberality, luxury; unfavourable news.",
            },
            {	"Knight of Pentacles",
                    "minp12",
                    "minp12",
                    "minp12",
                    "He rides a slow, enduring, heavy horse, to which his own aspect corresponds. He exhibits his symbol, but does not look therein.",
                    "Utility, serviceableness, interest, responsibility, rectitude-all on the normal and external plane.",
                    "Reversed: inertia, idleness, repose of that kind, stagnation; also placidity, discouragement, carelessness.",
            },
            {	"Queen of Pentacles",
                    "minp13",
                    "minp13",
                    "minp13",
                    "The face suggests that of a dark woman, whose qualities might be summed up in the idea of greatness of soul; she has also the serious cast of intelligence; she contemplates her symbol and may see worlds therein.",
                    "Opulence, generosity, magnificence, security, liberty.",
                    "Reversed: Evil, suspicion, suspense, fear, mistrust.",
            },
            {	"King of Pentacles",
                    "minp14",
                    "minp14",
                    "minp14",
                    "The...face is rather dark, suggesting also courage, but somewhat lethargic in tendency. The bull's head should be noted as a recurrent symbol on the throne. The sign of this suit is represented throughout as engraved or blazoned with the pentagram, typifying the correspondence of the four elements in human nature and that by which they may be governed.*",
                    "Valour, realizing intelligence, business and normal intellectual aptitude, sometimes mathematical gifts and attainments of this kind; success in these paths.",
                    "Reversed: Vice, weakness, ugliness, perversity, corruption, peril.",
            },
            {	"Ace of Cups",
                    "minc01",
                    "minc01",
                    "minc01",
                    "The waters are beneath, and thereon are water-lilies; the hand issues from the cloud, holding in its palm the cup, from which four streams are pouring; a dove, bearing in its bill a cross-marked Host, descends to place the Wafer in the Cup; the dew of water is falling on all sides. It is an intimation of that which may lie behind the Lesser Arcana.",
                    "House of the true heart, joy, content, abode, nourishment, abundance, fertility; Holy Table, felicity hereof.",
                    "Reversed: House of the false heart, mutation, instability, revolution.",
            },
            {	"Two of Cups",
                    "minc02",
                    "minc02",
                    "minc02",
                    "A youth and maiden are pledging one another, and above their cups rises the Caduceus of Hermes, between the great wings of which there appears a lion's head. It is a variant of a sign which is found in a few old examples of this card. Some curious emblematical meanings are attached to it, buoutt they do not concern us in this place.",
                    "Love, passion, friendship, affinity, union, concord, sympathy, the interrelation of the sexes, and—as a suggestion apart from all offices of divination—that desire which is not in Nature, but by which Nature is sanctified. Favourable in things of pleasure and business, as well as love; also wealth and honour.",
                    "Reversed: Passion.",
            },
            {	"Three of Cups",
                    "minc03",
                    "minc03",
                    "minc03",
                    "Maidens in a garden-ground with cups uplifted, as if pledging one another.",
                    "The conclusion of any matter in plenty, perfection and merriment; happy issue, victory, fulfilment, solace, healing.",
                    "Reversed: Expedition, dispatch, achievement, end. It signifies also the side of excess in physical enjoyment, and the pleasures of the senses.",
            },
            {	"Four of Cups",
                    "minc04",
                    "minc04",
                    "minc04",
                    "A young man is seated under a tree and contemplates three cups set on the grass before him; an arm issuing from a cloud offers him another cup. His expression notwithstanding is one of discontent with his environment.",
                    "Weariness, disgust, aversion, imaginary vexations, as if the wine of this world had caused satiety only; another wine, as if a fairy gift, is now offered the wastrel, but he sees no consolation therein. This is also a card of blended pleasure.",
                    "Reversed: Novelty, presage, new instruction, new relations.",
            },
            {	"Five of Cups",
                    "minc05",
                    "minc05",
                    "minc05",
                    "A dark, cloaked figure, looking sideways at three prone cups two others stand upright behind him; a bridge is in the background, leading to a small keep or holding.",
                    "It is a card of loss, but something remains over; three have been taken, but two are left; it is a card of inheritance, patrimony, transmission, but not corresponding to expectations; with some interpreters it is a card of marriage, but not without bitterness or frustration.",
                    "Reversed: News, alliances, affinity, consanguinity, ancestry, return, false projects.",
            },
            {	"Six of Cups",
                    "minc06",
                    "minc06",
                    "minc06",
                    "Children in an old garden, their cups filled with flowers.",
                    "A card of the past and of memories, looking back, as—for example—on childhood; happiness, enjoyment, but coming rather from the past; things that have vanished. Another reading reverses this, giving new relations, new knowledge, new environment, and then the children are disporting in an unfamiliar precinct.",
                    "Reversed: The future, renewal, that which will come to pass presently.",
            },
            {	"Seven of Cups",
                    "minc07",
                    "minc07",
                    "minc07",
                    "Strange chalices of vision, but the images are more especially those of the fantastic spirit.",
                    "Fairy favours, images of reflection, sentiment, imagination, things seen in the glass of contemplation; some attainment in these degrees, but nothing permanent or substantial is suggested.",
                    "Reversed: Desire, will, determination, project.",
            },
            {	"Eight of Cups",
                    "minc08",
                    "minc08",
                    "minc08",
                    "A man of dejected aspect is deserting the cups of his felicity, enterprise, undertaking or previous concern.",
                    "The card speaks for itself on the surface, but other readings are entirely antithetical—giving joy, mildness, timidity, honour, modesty. In practice, it is usually found that the card shews the decline of a matter, or that a matter which has been thought to be important is really of slight consequence—either for good or evil.",
                    "Reversed: Great joy, happiness, feasting.",
            },
            {	"Nine of Cups",
                    "minc09",
                    "minc09",
                    "minc09",
                    "A goodly personage has feasted to his heart's content, and abundant refreshment of wine is on the arched counter behind him, seeming to indicate that the future is also assured. The picture offers the material side only, but there are other aspects.",
                    "Concord, contentment, physical <em>bien-être</em>; also victory, success, advantage; satisfaction for the Querent or person for whom the consultation is made.",
                    "Reversed: Truth, loyalty, liberty; but the readings vary and include mistakes, imperfections, etc.",
            },
            {	"Ten of Cups",
                    "minc10",
                    "minc10",
                    "minc10",
                    "Appearance of Cups in a rainbow; it is contemplated in wonder and ecstacy by a man and woman below, evidently husband and wife. His right arm is about her; his left is raised upward; she raises her right arm. The two children dancing near them have not observed the prodigy but are happy after their own manner. There is a home-scene beyond.",
                    "Contentment, repose of the entire heart; the perfection of that state; also perfection of human love and friendship; if with several picture-cards, a person who is taking charge of the Querent's interests; also the town, village or country inhabited by the Querent.",
                    "Reversed: Repose of the false heart, indignation, violence.",
            },
            {	"Page of Cups",
                    "minc11",
                    "minc11",
                    "minc11",
                    "A fair, pleasing, somewhat effeminate page, of studious and intent aspect, contemplates a fish rising from a cup to look at him. It is the pictures of the mind taking form.",
                    "Fair young man, one impelled to render service and with whom the Querent will be connected; a studious youth; news, message; application, reflection, meditation; also these things directed to business.",
                    "Reversed: Taste, inclination, attachment, seduction, deception, artifice.",
            },
            {	"Knight of Cups",
                    "minc12",
                    "minc12",
                    "minc12",
                    "Graceful, but not warlike; riding quietly, wearing a winged helmet, referring to those higher graces of the imagination which sometimes characterize this card. He too is a dreamer, but the images of the side of sense haunt him in his vision.",
                    "Arrival, approach—sometimes that of a messenger; advances, proposition, demeanour, invitation, incitement.",
                    "Reversed: Trickery, artifice, subtlety, swindling, duplicity, fraud.",
            },
            {	"Queen of Cups",
                    "minc13",
                    "minc13",
                    "minc13",
                    "Beautiful, fair, dreamy—as one who sees visions in a cup. This is, however, only one of her aspects; she sees, but she also acts, and her activity feeds her dream.",
                    "Good, fair woman; honest, devoted woman, who will do service to the Querent; loving intelligence, and hence the gift of vision; success, happiness, pleasure; also wisdom, virtue; a perfect spouse and a good mother.",
                    "Reversed: The accounts vary; good woman; otherwise, distinguished woman but one not to be trusted; perverse woman; vice, dishonour, depravity.",
            },
            {	"King of Cups",
                    "minc14",
                    "minc14",
                    "minc14",
                    "He holds a short sceptre in his left hand and a great cup in his right; his throne is set upon the sea; on one side a ship is riding and on the other a dolphin is leaping. The implicit is that the Sign of the Cup naturally refers to water, which appears in all the court cards.",
                    "Fair man, man of business, law, or divinity; responsible, disposed to oblige the Querent; also equity, art and science, including those who profess science, law and art; creative intelligence.",
                    "Reversed: Dishonest, double-dealing man; roguery, exaction, injustice, vice, scandal, pillage, considerable loss.",
            },
            {	"Ace of Swords",
                    "mins01",
                    "mins01",
                    "mins01",
                    "A hand issues from a cloud, grasping as word, the point of which is encircled by a crown.",
                    "Triumph, the excessive degree in everything, conquest, triumph of force. It is a card of great force, in love as well as in hatred. The crown may carry a much higher significance than comes usually within the sphere of fortune-telling.",
                    "Reversed: The same, but the results are disastrous; another account says—conception, childbirth, augmentation, multiplicity.",
            },
            {	"Two of Swords",
                    "mins02",
                    "mins02",
                    "mins02",
                    "A hoodwinked female figure balances two swords upon her shoulders.",
                    "Conformity and the equipoise which it suggests, courage, friendship, concord in a state of arms; another reading gives tenderness, affection, intimacy. The suggestion of harmony and other favourable readings must be considered in a qualified manner, as Swords generally are not symbolical of beneficent forces in human affairs.",
                    "Reversed: Imposture, falsehood, duplicity, disloyalty.",
            },
            {	"Three of Swords",
                    "mins03",
                    "mins03",
                    "mins03",
                    "Three swords piercing a heart; cloud and rain behind.",
                    "Removal, absence, delay, division, rupture, dispersion, and all that the design signifies naturally, being too simple and obvious to call for specific enumeration.",
                    "Reversed: Mental alienation, error, loss, distraction, disorder, confusion.",
            },
            {	"Four of Swords",
                    "mins04",
                    "mins04",
                    "mins04",
                    "The effigy of a knight in the attitude of prayer, at full length upon his tomb.",
                    "Vigilance, retreat, solitude, hermit's repose, exile, tomb and coffin. It is these last that have suggested the design.",
                    "Reversed: Wise administration, circumspection, economy, avarice, precaution, testament.",
            },
            {	"Five of Swords",
                    "mins05",
                    "mins05",
                    "mins05",
                    "A disdainful man looks after two retreating and dejected figures. Their swords lie upon the ground. He carries two others on his left shoulder, and a third sword is in his right hand, point to earth. He is the master in possession of the field.",
                    "Degradation, destruction, revocation, infamy, dishonour, loss, with the variants and analogues of these.",
                    "Reversed: The same; burial and obsequies.",
            },
            {	"Six of Swords",
                    "mins06",
                    "mins06",
                    "mins06",
                    "A ferryman carrying passengers in his punt to the further shore. The course is smooth, and seeing that the freight is light, it may be noted that the work is not beyond his strength.",
                    "Journey by water, route, way, envoy, commissionary, expedient.",
                    "Reversed: Declaration, confession, publicity; one account says that it is a proposal of love.",
            },
            {	"Seven of Swords",
                    "mins07",
                    "mins07",
                    "mins07",
                    "A man in the act of carrying away five swords rapidly; the two others of the card remain stuck in the ground. A camp is close at hand.",
                    "Design, attempt, wish, hope, confidence; also quarrelling, a plan that may fail, annoyance. The design is uncertain in its import, because the significations are widely at variance with each other.",
                    "Reversed: Good advice, counsel, instruction, slander, babbling.",
            },
            {	"Eight of Swords",
                    "mins08",
                    "mins08",
                    "mins08",
                    "A woman, bound and hoodwinked, with the swords of the card about her. Yet it is rather a card of temporary durance than of irretrievable bondage.",
                    "Bad news, violent chagrin, crisis, censure, power in trammels, conflict, calumny; also sickness.",
                    "Reversed: Disquiet, difficulty, opposition, accident, treachery; what is unforeseen; fatality.",
            },
            {	"Nine of Swords",
                    "mins09",
                    "mins09",
                    "mins09",
                    "One seated on her couch in lamentation, with the swords over her. She is as one who knows no sorrow which is like unto hers. It is a card of utter desolation.",
                    "Death, failure, miscarriage, delay, deception, disappointment, despair.",
                    "Reversed: Imprisonment, suspicion, doubt, reasonable fear, shame.",
            },
            {	"Ten of Swords",
                    "mins10",
                    "mins10",
                    "mins10",
                    "A prostrate figure, pierced by all the swords belonging to the card.",
                    "Whatsoever is intimated by the design; also pain, affliction, tears, sadness, desolation. It is not especially a card of violent death.",
                    "Reversed: Advantage, profit, success, favour, but none of these are permanent; also power and authority.",
            },
            {	"Page of Swords",
                    "mins11",
                    "mins11",
                    "mins11",
                    "A lithe, active figure holds a sword upright in both hands, while in the act of swift walking. He is passing over rugged land, and about his way the clouds are collocated wildly. He is alert and lithe, looking this way and that, as if an expected enemy might appear at any moment.",
                    "Authority, overseeing, secret service, vigilance, spying, examination, and the qualities thereto belonging.",
                    "Reversed: More evil side of these qualities; what is unforeseen, unprepared state; sickness is also intimated.",
            },
            {	"Knight of Swords",
                    "mins12",
                    "mins12",
                    "mins12",
                    "He is riding in full course, as if scattering his enemies. In the design he is really a prototypical hero of romantic chivalry. He might almost be Galahad, whose sword is swift and sure because he is clean of heart.",
                    "Skill, bravery, capacity, defence, address, enmity, wrath, war, destruction, opposition, resistance, ruin. There is therefore a sense in which the card signifies death, but it carries this meaning only in its proximity to other cards of fatality.",
                    "Reversed: Imprudence, incapacity, extravagance.",
            },
            {	"Queen of Swords",
                    "mins13",
                    "mins13",
                    "mins13",
                    "Her right hand raises the weapon vertically and the hilt rests on an arm of her royal chair the left hand is extended, the arm raised her countenance is severe but chastened; it suggests familiarity with sorrow. It does not represent mercy, and, her sword notwithstanding, she is scarcely a symbol of power.",
                    "Widowhood, female sadness and embarrassment, absence, sterility, mourning, privation, separation.",
                    "Reversed: Malice, bigotry, artifice, prudery, bale, deceit.",
            },
            {	"King of Swords",
                    "mins14",
                    "mins14",
                    "mins14",
                    "He sits in judgment, holding the unsheathed sign of his suit. He recalls, of course, the conventional Symbol of justice in the Trumps Major, and he may represent this virtue, but he is rather the power of life and death, in virtue of his office.",
                    "Whatsoever arises out of the idea of judgment and all its connexions-power, command, authority, militant intelligence, law, offices of the crown, and so forth.",
                    "Reversed: Cruelty, perversity, barbarity, perfidy, evil intention.",
            }
    };

}
