package crunchypencil.com.tarot1;
/**
 * Created by davidcahill on 11/12/14.
 */
public class Deck {
    static boolean soundon = true;
    static int count = 0;
    static int[] tempdeck = new int[78]; // length of the deck
    static int[] temparray = Deck.makeArray(); // make dummy array to shuffle
    public static int[] makeArray() {
        int[] sample = new int[Deck.tempdeck.length];
        for (int i = 0; i < sample.length; i++) {
            sample[i] = i;
        }
        return sample;
    }
    public static int[] shuffleArray(int[] numbers) {
        for (int i = numbers.length - 1; i > 0; i--) {
            int select = (int) (Math.random() * (i + 1)); // 0 <= select <= i
            // swap current value with selected value
            int temp = numbers[i];
            numbers[i] = numbers[select];
            numbers[select] = temp;
        }
        return numbers;
    }
    static String[][] tarotdeck = new String[78][];

    public static String[][] addFlip(String[][] decktoadd){
        for(int i=0;i<78;i++){
            double invran = Math.random();
            if (invran <= .5) {
                decktoadd[i][1] = "false";
            } else {
                decktoadd[i][1] = "true";
            }
        }
        return decktoadd;
    }
    static String[][] deck = new String[][] {
            {    "0 - The Fool",
                    "maj00",
                    "maj00",
                    "maj00",
                    "With light step, a young man in garish vestments pauses at the brink of a precipice among the great heights of the world; he surveys the expanse of sky rather than the edge below which opens on the depth. It is as if angels were waiting to uphold him, if he leaped from the height. His countenance of expectant dream. He has a rose in one hand and in the other a staff, suspending his possessions and a dog, as distracted as he is.",
                    "Beginnings, innocence, spontaneity, a free spirit, folly, optimism, delirium.",
                    "Reversed: Negligence, naivety, foolishness, recklessness, risk-taking, carelessness, apathy, vanity."
            },
            {    "I - The Magician",
                    "maj01",
                    "maj01",
                    "maj01",
                    "A youthful figure in a robe, with smile of confidence upholds a wand in front of a table in a garden and his other hand points to the ground. Above his head is the mysterious sign of infinity. His belt is a serpent biting it's own tail. On the table in front of him are the symbols of the four Tarot suits, signifying the elements of natural life.",
                    "Power, skill, concentration, action, resourcefulness, diplomacy, self-confidence, a strong will.",
                    "Reversed: Manipulation, poor planning, latent talents, disgrace, disquiet."
            },
            {    "II - The High Priestess",
                    "maj02",
                    "maj02",
                    "maj02",
                    "She has the lunar crescent at her feet, a horned diadem on her head with a globe in the middle, and a large solar cross on her breast. The scroll in her hands is inscribed with the word TORA, signifying the Law and the Word. She is seated between a white and a black pillar inscribed with a J and a B. She is the spiritual Bride and Mother, the daughter of the stars and the Higher Garden of Eden.",
                    "Intuition, the subconscious, secrets, the future as yet unrevealed, inaction, wisdom, science.",
                    "Reversed: Passion, hidden agendas, conceit, surface knowledge, the need to listen to the inner voice.",
            },
            {    "III - The Empress",
                    "maj03",
                    "maj03",
                    "maj03",
                    "A stately figure, seated with rich vestments, she is a daughter of Heaven and Earth. Her diadem is of twelve stars, gathered in a cluster. The symbol of Venus is on the shield which rests near her. She is in a garden growing grain in front of a waterfall. She is the inferior Garden of Eden, the Earthly Paradise.",
                    "Fertility, femininity, beauty, nature, abundance, action, initiative, life in bloom.",
                    "Reversed: Creative block, dependence on others.",
            },
            {    "IV - The Emperor",
                    "maj04",
                    "maj04",
                    "maj04",
                    "He has an Ankh for his scepter and a globe in his left hand. He is a crowned monarch—commanding, stately, seated on a throne, the arms of which are fronted by rams' heads. He is executive and realization, the power of this world, clothed in authority.",
                    "Authority, father-figure, stability, power, protection, reason, conviction, will, a solid foundation.",
                    "Reversed:  Domination, excessive control, rigidity, inflexibility, obstruction, immaturity.",
            },
            {    "V - The Hierophant",
                    "maj05",
                    "maj05",
                    "maj05",
                    "He wears a triple crown and is seated between two pillars. He holds a scepter terminating in the triple cross, and with his right hand he gives the ecclesiastical sign. At his feet are crossed keys, and two priestly ministers kneel before him.",
                    "Alliance, captivity, mercy and goodness, inspiration, religion, society, conformity, tradition, beliefs.",
                    "Reversed: Weakness, restriction, challenging the status quo.",
            },
            {    "VI - The Lovers",
                    "maj06",
                    "maj06",
                    "maj06",
                    "The sun shines in the zenith, and beneath is a great winged figure with arms extended. In the foreground are Adam and Eve when they first occupied the garden of Eden. Behind the man is the Tree of Life, bearing twelve fruits, and the Tree of the Knowledge of Good and Evil is behind the woman with the serpent.",
                    "Attraction, sexuality, love, union, relationships, values alignment, choices, beauty, trials overcome.",
                    "Reversed: Failure, foolish designs, disharmony, imbalance, misalignment of values.",
            },
            {    "VII - The Chariot",
                    "maj07",
                    "maj07",
                    "maj07",
                    "An erect and princely figure is crowned and at the control of a chariot. He has led conquest on all planes—in the mind, in science, in progress, in trials of initiation. Two sphinxes thus draw his chariot.",
                    "Movement, progress, providence, war, triumph, will power, victory, assertion.",
                    "Reversed: Riot, quarrel, dispute, lack of control, aggression, litigation.",
            },
            {    "VIII - Strength",
                    "maj08",
                    "maj08",
                    "maj08",
                    "A woman, over whose head there broods the symbol of life which we see in the card of the Magician, is calmly closing the jaws of a lion.",
                    "Power, energy, courage, patience, control, compassion, integration of animal self.",
                    "Reversed: Despotism, abuse if power, Weakness, self-doubt, lack of self-discipline, discord.",
            },
            {    "IX - The Hermit",
                    "maj09",
                    "maj09",
                    "maj09",
                    "The Hermit is said to be in search of Truth, and of Justice which has preceded him on the way. His lantern contains the Light of Inner Guidance and he carries the staff of wisdom.",
                    "Meditation, prudence, soul-searching, introspection, being alone, inner guidance.",
                    "Reversed: Concealment, disguise, isolation, loneliness, withdrawal, unreasoned caution.",
            },
            {    "X - Wheel of Fortune",
                    "maj10",
                    "maj10",
                    "maj10",
                    "Magical beasts surrounding the wheel embody knowledge. This symbolic picture stands for the perpetual motion of a fluidic universe and for the flux of human life. The word TARO can be reversed as ROTA, inscribed on the wheel, counterchanged with the letters of the Divine Name.",
                    "Destiny, fortune, success, good luck, karma, life cycles, destiny, a turning point.",
                    "Reversed: Bad luck, lack of control, negative external forces, chaos.",
            },
            {    "XI - Justice",
                    "maj11",
                    "maj11",
                    "maj11",
                    "The figure is seated between the pillars of Justice. He upholds a sword and scales, representing Fairness and Law.",
                    "Equity, rightness, triumph of the deserving side in law, fairness, truth, cause and effect",
                    "Reversed: Legal complications, unfairness, lack of accountability, dishonesty, bigotry, bias.",
            },
            {    "XII - The Hanged Man",
                    "maj12",
                    "maj12",
                    "maj12",
                    "The gallows from which he is suspended forms a cross. There is an aura about the head of this seeming martyr. His figure suggests life in suspension, but not death. He is deep in meditation, accepting his fate, and wiser for it.",
                    "Wisdom, trials, surrender, sacrifice, intuition, a new perspective, letting go.",
                    "Reversed: Martyrdom, indecision, delay.",
            },
            {    "XIII - Death",
                    "maj13",
                    "maj13",
                    "maj13",
                    "The mysterious horseman moves slowly, bearing a black banner emblazoned with the Mystic Rose which signifies life. Between two pillars on the horizon there shines the sun of immortality. The horseman carries no visible weapon, but king and child and maiden fall before him, while a prelate with clasped hands awaits his end.",
                    "End, mortality, destruction, beginnings, change, transformation, transition.",
                    "Reversed: Lethargy, resistance to change, unable to move on",
            },
            {    "XIV - Temperance",
                    "maj14",
                    "maj14",
                    "maj14",
                    "A winged angel, with the sign of the sun upon his forehead and on his breast the square and triangle of the septenary. He is pouring the essences of life from chalice to chalice. He has one foot upon the earth and one upon water. A direct path goes up to the horizon, and above there is a great light, through which a crown is seen vaguely.",
                    "Economy, moderation, frugality, accommodation, patience, purpose, meaning.",
                    "Reversed: Competing interests, imbalance, excess, lack of long-term vision, disunion.",
            },
            {    "XV - The Devil",
                    "maj15",
                    "maj15",
                    "maj15",
                    "The Horned Goat of Mendes with wings like a bat is standing on an altar. The right hand is upraised and extended, the reverse of the benediction given by the Hierophant. In the left hand there is a great flaming torch pointing towards the earth. A reversed pentagram is on his forehead. On a ring on the alter is attached two devil figures, male and female, as if Adam and Eve after the Fall.",
                    "Ravage, violence, bondage, addiction, sexuality, materialism.",
                    "Reversed: Breaking free, detachment, power reclaimed.",
            },
            {    "XVI - The Tower",
                    "maj16",
                    "maj16",
                    "maj16",
                    "The Tower is struck by Lightning and set afire, blowing off the crown on top. Its two inhabitants fall to the depths below.",
                    "Unforeseen catastrophe, collapse of stable structures, upheaval, sudden change, revelation.",
                    "Reversed: Avoidance of disaster, fear of change",
            },
            {    "XVII - The Star",
                    "maj17",
                    "maj17",
                    "maj17",
                    "A great, radiant star, surrounded by seven lesser stars. The female figure in the foreground is naked. Her left knee is on the land and her right foot upon the water. She pours Water of Life from two great ewers, irrigating sea and land.",
                    "Hope and bright prospects, calm, a good omen, renewal, inspiration.",
                    "Reversed: Arrogance, lack of faith, despair, discouragement.",
            },
            {    "XVIII - The Moon",
                    "maj18",
                    "maj18",
                    "maj18",
                    "The moon's eyes are closed as if asleep, between two towers. A dog and a wolf howl and are accompanied by a crustacean emerging from the waters. They are the fears of the natural mind; the reflected light of the moon illuminating our animal nature.",
                    "Mystery, illusion, fear, anxiety, dreams, deception, error, subconscious.",
                    "Reversed: Release of fear, unhappiness, confusion.",
            },
            {    "XIX - The Sun",
                    "maj19",
                    "maj19",
                    "maj19",
                    "The naked child mounted on a white horse and flowers in it's hair upholds a pennant in a garden of sunflowers. It signifies the light of this world, typified by the heart of a child.",
                    "Material happiness, warmth, success, fortunate marriage, contentment.",
                    "Reversed: Temporary depression, lack of success.",
            },
            {    "XX - Judgment",
                    "maj20",
                    "maj20",
                    "maj20",
                    "A great angel is here encompassed by clouds, blowing his bannered trumpet with a cross displayed on his banner. The dead are rising from their tombs.",
                    "Change of position, renewal, rebirth, inner calling, ",
                    "Reversed: Weakness, self-doubt, refusal of self-examination.",
            },
            {    "XXI - The World",
                    "maj21",
                    "maj21",
                    "maj21",
                    "The four living creatures of the Apocalypse, attributed to the evangelists in Christian symbolism, are grouped about an elliptic garland. Within this garland there is the figure of a woman, wearing only a light scarf. In the act of dancing, she has a wand in either hand.",
                    "Assured success, voyage, emigration, completion, integration, accomplishment.",
                    "Reversed: Stagnation, lack of completion, lack of closure.",
            },
            {    "Ace of Wands",
                    "minw01",
                    "minw01",
                    "minw01",
                    "A magical hand immerging from a cloud or smoke upholds a wand growing with leaves.",
                    "Creation, invention, enterprise, beginning, the starting point of enterprises, potential.",
                    "Reversed: Fall, decadence, delay, lack of motivation.",
            },
            {    "Two of Wands",
                    "minw02",
                    "minw02",
                    "minw02",
                    "A tall man looks from a battlemented roof over sea and shore; he holds a globe in his right hand and a staff in his left rests on the battlement. The second staff is fixed upright in a ring. A rose and a cross and a lily are shown in an emblem.",
                    "Contemplation, future planning, progress, decisions, discovery.",
                    "Reversed: Fear of the unknown, lack of planning.",
            },
            {    "Three of Wands",
                    "minw03",
                    "minw03",
                    "minw03",
                    "A calm, stately personage, with his back turned, looking from a cliff's edge at ships passing over the sea. Three staves are planted in the ground, and he leans slightly on one of them.",
                    "Preparation, safety, foresight, enterprise, the home.",
                    "Reversed: Lack of foresight, delays, obstacles to long-term goals.",
            },
            {    "Four of Wands",
                    "minw04",
                    "minw04",
                    "minw04",
                    "From the four great staves planted in the foreground there is a great garland suspended; two female figures uplift bouquets; at their side is a bridge over a moat, leading to an old castle.",
                    "Celebration, harmony, marriage, home, community.",
                    "Reversed: A breakdown in communication, transition.",
            },
            {    "Five of Wands",
                    "minw05",
                    "minw05",
                    "minw05",
                    "A group of youths, brandishing staves are fighting in sport or in strife. It is mimic warfare.",
                    "Disagreement, competition, strife, tension, minor conflict.",
                    "Reversed: Litigation, conflict avoidance, diversity, agreeing to disagree.",
            },
            {    "Six of Wands",
                    "minw06",
                    "minw06",
                    "minw06",
                    "A laurelled horseman bears a staff adorned with a laurel crown. Footmen with staves are at his side.",
                    "Public recognition, victory, progress, self-confidence, achievement.",
                    "Reversed: Egotism, disrepute, lack of confidence, fall from grace.",
            },
            {    "Seven of Wands",
                    "minw07",
                    "minw07",
                    "minw07",
                    "A young man on a cliff is brandishing a staff as if fighting six other staves, raised towards him from below.",
                    "Defensiveness, on-guard, challenge, competition.",
                    "Reversed: Giving up, overwhelmed, overly protective.",
            },
            {    "Eight of Wands",
                    "minw08",
                    "minw08",
                    "minw08",
                    "The card represents motion through the immovable - a flight of wands through an open country.",
                    "Speed, action, air travel, movement, swift change.",
                    "Reversed: Delays, frustration, holding off.",
            },
            {    "Nine of Wands",
                    "minw09",
                    "minw09",
                    "minw09",
                    "A figure with a bandage on his head leans upon his staff and has an expectant look, as if awaiting an enemy. Behind are eight other staves—erect, in orderly disposition.",
                    "Courage, pessimism, persistence, test of faith, resilience.",
                    "Reversed: On edge, defensive, hesitant, paranoia.",
            },
            {    "Ten of Wands",
                    "minw10",
                    "minw10",
                    "minw10",
                    "A man is oppressed by the weight of the ten staves which he is attempting to carry.",
                    "Burden, oppression, responsibilities, hard work, stress.",
                    "Reversed: Taking on too much, avoiding responsibility.",
            },
            {    "Page of Wands",
                    "minw11",
                    "minw11",
                    "minw11",
                    "A young man stands in the act of proclamation, inspired by the staff he is holding.",
                    "Inspiration, enthusiasm, exploration, discovery, free spirit.",
                    "Reversed: Setbacks to new ideas, pessimism, lack of direction.",
            },
            {    "Knight of Wands",
                    "minw12",
                    "minw12",
                    "minw12",
                    "He is upon a journey, armed with a short wand, and although armored, he is not warlike. The motion of the horse is a key to the character of its rider.",
                    "Energy, passion, risk-taker, lust, action, adventure, impulsiveness.",
                    "Reversed: Haste, scattered energy, delays, frustration.",
            },
            {    "Queen of Wands",
                    "minw13",
                    "minw13",
                    "minw13",
                    "The Queen sits upon a decorated throne with a staff and a sunflower, accompanied by a black cat. Her face is confident and determined.",
                    "Confident, focused, exuberance, warmth, vibrancy, determination.",
                    "Reversed: Shrinking violet, aggressive, demanding.",
            },
            {    "King of Wands",
                    "minw14",
                    "minw14",
                    "minw14",
                    "The king is a serious man, an animated, impassioned, noble. He holds a flowering wand. He connects with the symbol of the lion, which is emblazoned on the back of his throne. A lizard is at his feet, also on his throne.",
                    "Career-focused, a natural-born leader, vision, entrepreneur, honor.",
                    "Reversed: Impulsiveness, haste, ruthless, high expectations.",
            },
            {    "Ace of Pentacles",
                    "minp01",
                    "minp01",
                    "minp01",
                    "A hand—issuing from a cloud—holds up a pentacle above a garden of flowers.",
                    "Manifestation, new financial opportunity, prosperity, clarity of life purpose.",
                    "Reversed: Lost opportunity, lack of planning and foresight.",
            },
            {    "Two of Pentacles",
                    "minp02",
                    "minp02",
                    "minp02",
                    "A young man in the act of dancing has a pentacle in either hand. They are joined by an endless cord which is like the number 8 reversed.",
                    "Balance, adaptability, time management, prioritization, multitasking.",
                    "Reversed: Disorganization, financial disarray.",
            },
            {    "Three of Pentacles",
                    "minp03",
                    "minp03",
                    "minp03",
                    "A sculptor is at his work in a monastery. This apprentice has received his payment and is now at work in earnest.",
                    "Teamwork, initial fulfillment, collaboration, learning, suitable career.",
                    "Reversed: Lack of teamwork, disregard for skills.",
            },
            {    "Four of Pentacles",
                    "minp04",
                    "minp04",
                    "minp04",
                    "A crowned figure has a pentacle over his crown, he clasps another with hands and arms. Two pentacles are under his feet. He holds on to that which he has.",
                    "Control, stability, security, possession, conservatism.",
                    "Reversed: Greed, materialism, self-protection.",
            },
            {    "Five of Pentacles",
                    "minp05",
                    "minp05",
                    "minp05",
                    "Two beggars in a snowstorm pass a church with a lighted window bearing five pentacles.",
                    "Isolation, insecurity, worry, financial loss, poverty, feeling as an outsider.",
                    "Reversed: Recovery from financial loss, spiritual poverty.",
            },
            {    "Six of Pentacles",
                    "minp06",
                    "minp06",
                    "minp06",
                    "A person in the guise of a merchant weighs money in a pair of scales and distributes it to the needy and distressed. It is a testimony to his own success in life, as well as to his goodness of heart.",
                    "Generosity, charity, accepting and giving help, prosperity, sharing wealth.",
                    "Reversed: Debt, selfishness, one-sided charity.",
            },
            {    "Seven of Pentacles",
                    "minp07",
                    "minp07",
                    "minp07",
                    "A young man, leaning on his staff, looks intently at seven pentacles attached to a clump of greenery on his right; one would say that these were his treasures and his investment growing.",
                    "Vision, perseverance, profit, investment, waiting for plans to bear fruit.",
                    "Reversed: Lack of long-term vision, limited success or reward.",
            },
            {    "Eight of Pentacles",
                    "minp08",
                    "minp08",
                    "minp08",
                    "An artist is at work, which he exhibits in the form of trophies displayed on a tree.",
                    "Work, employment, apprenticeship, education, laying the groundwork, engagement.",
                    "Reversed: Voided ambition, perfectionism, lacking focus, lacking foundation.",
            },
            {    "Nine of Pentacles",
                    "minp09",
                    "minp09",
                    "minp09",
                    "A woman with a bird upon her wrist stands amidst an abundance of grapevines in the garden of a manor. It is a luxurious domain, suggesting plenty in all things.",
                    "Gratitude, luxury, self-sufficiency, material comforts.",
                    "Reversed: Over-investment in work, financial setbacks.",
            },
            {    "Ten of Pentacles",
                    "minp10",
                    "minp10",
                    "minp10",
                    "A man and woman beneath an archway which gives entrance to a house and domain. They are accompanied by a child, who looks curiously at their two dogs accosting an ancient person seated in the foreground.",
                    "Gain, riches, inheritance, family, retirement, business relationships.",
                    "Reversed: Financial failure, loneliness, loss.",
            },
            {    "Page of Pentacles",
                    "minp11",
                    "minp11",
                    "minp11",
                    "A youthful figure, looking intently at the pentacle which hovers over his raised hands. He moves slowly, insensible of that which is about him.",
                    "Application, student, financial opportunity, new job.",
                    "Reversed: Lack of progress and planning, short-term focus.",
            },
            {    "Knight of Pentacles",
                    "minp12",
                    "minp12",
                    "minp12",
                    "Armored, the Knight rides a slow, enduring, heavy horse. He exhibits his symbol, but does not look at it.",
                    "Utility, serviceableness, cautious, routine, conservatism, methodical, slow to progress.",
                    "Reversed: Idleness, carelessness, laziness, boredom, feeling ‘stuck’.",
            },
            {    "Queen of Pentacles",
                    "minp13",
                    "minp13",
                    "minp13",
                    "A solitary woman sits upon a throne decorated with goats and angels. She is in a garden, accompanied by a rabbit. In her hand she contemplates the Pentacle.",
                    "Generosity, practical, motherly, grounded, calm, down-to-earth, security.",
                    "Reversed: Imbalance in work and family commitments.",
            },
            {    "King of Pentacles",
                    "minp14",
                    "minp14",
                    "minp14",
                    "The King holds his scepter; his face is rather dark, suggesting both courage and lethargy as he contemplates the pentacle. He sits upon a throne decorated with bull's heads in front of his elaborate castle.",
                    "Security, control, enjoys the good life, abundance, financially secure.",
                    "Reversed: Authoritative, domineering, controlling.",
            },
            {    "Ace of Cups",
                    "minc01",
                    "minc01",
                    "minc01",
                    "A hand issues from the cloud, holding in its palm the cup, from which four streams are pouring to the waters beneath, filled with water lilies. A dove, bearing in its bill a cross-marked Host, descends to place the Wafer in the Cup.",
                    "House of the true heart, love, compassion, creativity, overwhelming emotion.",
                    "Reversed: House of the false heart, blocked or repressed emotions.",
            },
            {    "Two of Cups",
                    "minc02",
                    "minc02",
                    "minc02",
                    "A youth and maiden are pledging their love to one another, and above their cups rises the Caduceus of Hermes, between the great wings of which there appears a lion's head.",
                    "Unified love, partnership, attraction, relationships, compatibility.",
                    "Reversed: Break-up, imbalance in a relationship, lack of harmony.",
            },
            {    "Three of Cups",
                    "minc03",
                    "minc03",
                    "minc03",
                    "Maidens in a garden-ground with cups uplifted, as if pledging to one another.",
                    "Celebration, friendship, creativity, community, laughter.",
                    "Reversed: An affair, 'three’s a crowd', stifled creativity.",
            },
            {    "Four of Cups",
                    "minc04",
                    "minc04",
                    "minc04",
                    "A young man is seated under a tree and contemplates three cups set on the grass before him; an arm issuing from a cloud offers him another cup. His expression is one of discontent with his environment.",
                    "Meditation, contemplation, apathy, re-evaluation.",
                    "Reversed: Boredom, missed opportunity, being aloof.",
            },
            {    "Five of Cups",
                    "minc05",
                    "minc05",
                    "minc05",
                    "A dark, cloaked figure, looking sideways at three spilled cups; two others stand upright behind him. A bridge is in the background, leading to a small castle.",
                    "Loss, regret, disappointment, despair, bereavement, self pity.",
                    "Reversed: Moving on, acceptance, forgiveness.",
            },
            {    "Six of Cups",
                    "minc06",
                    "minc06",
                    "minc06",
                    "Children in a garden, their six cups are filled with flowers.",
                    "Sentimentality, reunion, nostalgia, childhood memories, innocence.",
                    "Reversed: Stuck in the past, naivety, unrealistic.",
            },
            {    "Seven of Cups",
                    "minc07",
                    "minc07",
                    "minc07",
                    "Strange chalices filled with spiritual emblems are shown to an individual experiencing a vision.",
                    "Fantasy, illusion, wishful thinking, choices, indecision.",
                    "Reversed: Temptation, illusion, diversionary tactics.",
            },
            {    "Eight of Cups",
                    "minc08",
                    "minc08",
                    "minc08",
                    "A man of dejected aspect is deserting the foreground of eight cups, escaping at night.",
                    "Escapism, disappointment, abandoning something in search of something better.",
                    "Reversed: Hopelessness, aimless drifting, walking away.",
            },
            {    "Nine of Cups",
                    "minc09",
                    "minc09",
                    "minc09",
                    "A rich man has feasted to his heart's content, and abundant refreshment of wine is on the arched counter behind him. He is assured material satisfaction and wealth.",
                    "Wishes fulfilled, comfort, happiness, indulgence, self-satisfaction.",
                    "Reversed: Greed, dissatisfaction, materialism.",
            },
            {    "Ten of Cups",
                    "minc10",
                    "minc10",
                    "minc10",
                    "The appearance of Cups in a rainbow; it is contemplated in wonder by a man and woman below, evidently husband and wife. The two children dancing near them have not observed the prodigy but are happy in their own manner.",
                    "Harmony, marriage, happiness, attainment.",
                    "Reversed: Misalignment of values, broken home or marriage.",
            },
            {    "Page of Cups",
                    "minc11",
                    "minc11",
                    "minc11",
                    "A fair young man, lavishly dressed, contemplates a fish rising from a cup to speak to him.",
                    "A messenger, inspired, creative beginnings, synchronicity, learning artistic skill.",
                    "Reversed: Emotional immaturity, creative block.",
            },
            {    "Knight of Cups",
                    "minc12",
                    "minc12",
                    "minc12",
                    "Graceful, but not warlike, the knight rides quietly wearing a winged helmet. He is a dreamer, following his vision in the cup.",
                    "Romance, charm, ‘Knight in shining armor’, imagination, following one's heart.",
                    "Reversed: Unrealistic, jealousy, moodiness.",
            },
            {    "Queen of Cups",
                    "minc13",
                    "minc13",
                    "minc13",
                    "A beautiful woman sits on a throne at the edge of the sea. Her feet do not touch the water. She stares at a cup she cradles in her hands with handles shaped like praying angels.",
                    "Emotional security, nurturing, calm, intuitive, compassionate.",
                    "Reversed: Emotional insecurity, co-dependency.",
            },
            {    "King of Cups",
                    "minc14",
                    "minc14",
                    "minc14",
                    "He holds a short scepter in his left hand and a great cup in his right; his throne is set upon the sea; on one side a ship is riding and on the other a dolphin is leaping.",
                    "Emotional balance and control, generosity.",
                    "Reversed: Emotional manipulation, moodiness, volatility.",
            },
            {    "Ace of Swords",
                    "mins01",
                    "mins01",
                    "mins01",
                    "A hand issues from a cloud, grasping a sword, the point of which is encircled by a crown with hanging laurel.",
                    "A fresh start, opportunity, victory, breakthroughs, mental clarity.",
                    "Reversed: Confusion, chaos, lack of clarity.",
            },
            {    "Two of Swords",
                    "mins02",
                    "mins02",
                    "mins02",
                    "A blinded female figure balances two swords of equal size, seated at the seashore, beneath a crescent moon.",
                    "Indecision, choices, truce, stalemate, blocked emotions.",
                    "Reversed: Indecision, confusion, information overload.",
            },
            {    "Three of Swords",
                    "mins03",
                    "mins03",
                    "mins03",
                    "Three swords piercing a heart; cloud and rain behind.",
                    "Painful separation, sorrow heartbreak, grief, rejection, betrayal.",
                    "Reversed: Releasing pain, optimism, forgiveness.",
            },
            {    "Four of Swords",
                    "mins04",
                    "mins04",
                    "mins04",
                    "The effigy of a knight in prayer upon his place of burial. His tomb is decorated with swords.",
                    "Meditation, rest, contemplation, recuperation, passivity, retreat.",
                    "Reversed: Restlessness, burn-out, lack of progress.",
            },
            {    "Five of Swords",
                    "mins05",
                    "mins05",
                    "mins05",
                    "A disdainful man looks after two retreating and dejected figures; their swords lie discarded upon the ground. He carries two others on his shoulder, and a third sword is in his hand, pointed to the earth. He is the master in possession of this field.",
                    "Mind games, conflict, tension, loss, defeat, win at all costs, betrayal.",
                    "Reversed: Open to change, past resentment.",
            },
            {    "Six of Swords",
                    "mins06",
                    "mins06",
                    "mins06",
                    "A ferryman carrying passengers in his boat to the further shore. The water is smooth and his freight is light, so the work is not beyond his strength.",
                    "Leaving, regretful but necessary transition, rite of passage, going somewhere better.",
                    "Reversed: Cannot move on, carrying baggage.",
            },
            {    "Seven of Swords",
                    "mins07",
                    "mins07",
                    "mins07",
                    "A man is sneaking away from a nearby camp, in the act of carrying away five swords rapidly; the two others of the card remain stuck in the ground.",
                    "Secret plans, betrayal, deception, getting away with something, abandoning ship.",
                    "Reversed: Mental challenges, breaking free.",
            },
            {    "Eight of Swords",
                    "mins08",
                    "mins08",
                    "mins08",
                    "A woman is bound and blindfolded, imprisoned by the swords of the card about her.",
                    "Powerless, isolation, self-imposed restriction, imprisonment.",
                    "Reversed: Open to new perspectives, release.",
            },
            {    "Nine of Swords",
                    "mins09",
                    "mins09",
                    "mins09",
                    "One seated on her couch in lamentation, as if awoken from a nightmare, with the swords over her. She is as one who knows no sorrow which is like unto hers.",
                    "Overactive mind, depression, nightmares, intense anxiety, despair.",
                    "Reversed: Imprisonment, hopelessness, severe depression, torment.",
            },
            {    "Ten of Swords",
                    "mins10",
                    "mins10",
                    "mins10",
                    "A man is dead, pierced by all the swords belonging to the card. The sky is dark",
                    "Back-stabbed, defeat, self-sabotage, crisis, betrayal, endings, loss.",
                    "Reversed: Recovery, regeneration, fear of ruin, inevitable end.",
            },
            {    "Page of Swords",
                    "mins11",
                    "mins11",
                    "mins11",
                    "A lithe, active figure holds a sword upright in both hands. He is passing over rugged land. He looks back as if he is unsure of his decision.",
                    "Talkative, curious, mentally restless, acts without thinking, intellectually immature.",
                    "Reversed: All talk and no action, haste, undelivered promises.",
            },
            {    "Knight of Swords",
                    "mins12",
                    "mins12",
                    "mins12",
                    "He is riding in full course, as if scattering his enemies. Armored, he is out to destroy his enemies with his swift sword; he is certain he is clean of heart.",
                    "Fierce, determined, hasty, action-oriented, aggressively pursues goals.",
                    "Reversed: Scattered thought, disregard for consequences.",
            },
            {    "Queen of Swords",
                    "mins13",
                    "mins13",
                    "mins13",
                    "Her right hand holds the weapon vertically and the hilt rests on an arm of her royal chair the left hand is extended, the arm raised her countenance which is severe but chastened. Her face suggests familiarity with sorrow; it does not represent mercy.",
                    "Quick thinker, organized, perceptive, independent, communicative yet cold.",
                    "Reversed: Malice, overly-emotional, cold-hearted.",
            },
            {    "King of Swords",
                    "mins14",
                    "mins14",
                    "mins14",
                    "He sits in judgment, holding the unsheathed sign of his suit. He recalls the symbol of justice, but he is rather the power of life and death, in the virtue of his office.",
                    "Serious, clear thinking, rational intellectual power, authority, truth.",
                    "Reversed: Cruelty, perversity, manipulative, tyrannical, abusive.",
            }
    };
}
